### ISSUE TITLE
2.2.326 적용해봤습니다.

### ISSUE THREAD

**Issue by gogomasaru** [scouter-contrib/scouter-paper#108]
빠른 신규버전 배포 감사드립니다.
금일 2.2.326 적용해봤습니다.

1. 이전버전에서 일괄로 보인 아이콘이
- JBOSS : JBOSS(빨간글씨) 라고 보임
- 배치 : BATCH 라고 보임
- 데이터소스  : 디스크, 스토리지 형태 보임
- 리눅스 : 리눅스 아이콘 (펭귄) 보임
- websphere :  아래 처럼 보입니다.
![websphere](https://user-images.githubusercontent.com/26616377/47136686-6ba82b00-d2ef-11e8-97cf-ca7c72cfca6d.JPG)
혹시 제가 임의로 설정할수 있는 기능있는지 궁금합니다. client 프로그램에 edit object type에서 아이콘 설정있던데 변경하면 같이 바뀔까요?

2. 토플로지 그룹핑 잘됩니다.
- 모니터링 대상이 적으면 보기 좋은데, 많으면 그룹핑이 안되면 보기힘든면도 있습니다.
항목별로 그룹핑 설정이 되면 좋을 것 같습니다.
예) client, DB는 그룹핑, WAS는 그룹핑 해제

3. 아래는 어떤 기능인가요?
XLOG 프로파일러에서, 포함된 다른 XLOG로 이동할 수 있는 버튼이 추가되었습니다. 선택한 트랜잭션을 호출하거나, 트랜잭션에 호출한 다른 XLOG로 클릭하여 바로 이동할 수 있습니다.

- XLOG 프로파일링에서 클릭하면 동일한 service는 모두 음영표시 됩니다.
![xlog](https://user-images.githubusercontent.com/26616377/47137131-b7a79f80-d2f0-11e8-82ed-148c58a9612f.JPG)

**Comment by mindplates** [comment]
1. 위에 올려주신 아이콘은 페이퍼에서 등록되지 않은 아이콘인 경우에 표시되는 디폴트 이미지입니다.

현재 등록되어 있는 아이콘 명은 https://github.com/mindplates/scouter-paper/blob/master/src/common/PaperIcons.js 파일에 정의되어 있습니다. 

아이콘 명이 위 파일의 ObjectIcons의 이름 중에 포함된 경우, 아이콘이 출력이 됩니다. 아이콘은 fontawesome(https://fontawesome.com/)과 technology-icons(https://github.com/websiddu/technology-icons) 중에서 있는 것 위주로 적용하였고, 많이 사용할 것 같은데 아이콘이 위 두 파일에 없는 경우는 text로 표시되도록 처리하였습니다. 

말씀해주신 웹스피어는 현재 위 파일에 없어서, 기본값으로 나오는데, 웹스피어를 비롯한 누락된 WAS 들은 추가해보도록 하겠습니다!

2. 좋은 의견 감사합니다. 개별적인 토폴로지 그룹핑 부분은 좀 더 고민해봐서 진행봐야할 것 같습니다. 그룹핑에서 그룹핑을 푸는 컨트롤은 쉽게 만들 수 있을 것 같습니다만, 풀어진 상태를 큰 그룹으로 묶는게 생각보다 어려울 수 있을 것 같습니다. 이 부분은 좀 더 찾아보고 가능하다면 진행해보겠습니다!

3. 위 스크린샷에서 우측 상단에 'CURRENT : -3~~~'으로 시작되는 부분이 추가된 부분입니다. 또 위와 같은 버튼이 GENERAL INFO 밑에 프로파일들에도 있을 수 있습니다. 스카우터가 적용된 서버 A, B가 있고, 사용자 요청이 REST 방식으로 A -> B로 이동하여 처리되는 흐름인 경우, XLOG가 A에서 한번 B에서 한번 생기는데요, 이러한 경우 B의 XLOG에서 A로 이동할 수 있게, 위 버튼 처럼 추가되었습니다. A에서 B로는 프로파일 중간에 나타나게됩니다.

**Comment by kranian** [comment]
2. 토플로지 그룹핑  의견 부분은 #142 에서 개선 되었고, 릴리스 V2.5.0에 반영 되었습니다

작년 10월 이후 추가 의견이 없어 해당 이슈 종료하겠습니다.
