### ISSUE TITLE
리뷰 요청

### ISSUE THREAD

**Issue by gunlee01** [scouter-contrib/scouter-paper#114]
토폴로지에서 그루핑한 경우 인스턴스 숫자를 표시하도록 수정하였는데
노드를 움직이면 도장이 찍히듯이 그 글자가 5초마다 배경에 그려지는 현상이 있는데
원인을 찾을 수가 없습니다.
고수님 도와주세요.

`topology-group-instance-count` 브랜치에서 작업하였습니다.

- 브랜치 
  - https://github.com/mindplates/scouter-paper/tree/feature/topology-group-instance-count
- 커밋
  - @ 5f23c904c65ad5fdfa58ad8a6eb332427fe0f9b2

고치면 머지해주세요.
감사합니다.

**Comment by gunlee01** [comment]
이렇게 나와요...
![image](https://user-images.githubusercontent.com/6788732/47253609-4272d080-d490-11e8-8883-0925ee43220d.png)

**Comment by kranian** [comment]
검증 할수 있는 데모 scouter 환경 정보를 올려주세요 

보통 이런 현상은 D3 코드 중에 dom 에 데이터 갱신 후 erase가 수행이 안돼서 보통 일어나는데요

실제는 검증 환경에서 코드를 실행해 보고 수정을  할수 있을것 같네요

**Comment by gunlee01** [comment]
@kranian
Scouter Web API 서버 demo.scouterapm.com, 포트 6188 을 검증 환경으로 사용하고 있습니다.

**Comment by kranian** [comment]
![image](https://user-images.githubusercontent.com/18545293/47258493-df585c80-d4d6-11e8-9e60-22e7fad226c6.png)
  - 원인 알아내 수정해서 pull request 보냈습니다.. 그럼 수고하세요

**Comment by kranian** [comment]
풀 리퀘스트를 보내 내용을 보시면 아시겠지만 
원인은 단순합니다

인스턴스 수를 추가하는 클래스 선택 이름이 잘못돼서 그런거 였네요

**Comment by gunlee01** [comment]
감사합니다. 초고수님~

**Comment by kranian** [comment]
초고수는 아니지만 도움을 드려 제가 기쁘네요
그럼 수고하세요
