### ISSUE TITLE
고립망 페이지 연결 문의

### ISSUE THREAD

**Issue by leeyongsuk** [scouter-contrib/scouter-paper#124]
고립망에서 paper사용 시  외부에서 호출하는 css및 스크립트로 인해서 페이지 표시가 안되는 문제가 있습니다 혹시 별도로 제공 받을 수는 없을까요?

**Comment by mindplates** [comment]
답변이 늦어서 죄송합니다.
우선 현재 development 브렌치에 외부 리소스를 포함하도록 코드를 변경하였으며,
추가적으로 외부와 통신에 사용하는 부분이,
 - 업데이트 확인 (git)
 - 스크립트 에러 보고 (sentry)
위 두 부분이 있는데, 위 두 부분의 확인 기능을 Settings에서 선택할 수 있도록 개발하였습니다.
다음 릴리즈때(주중 예정) 업데이트하시거나, 혹은 development 브렌치를 빌드하여 사용하시면 문제가 해결될 것으로 생각됩니다.

**Comment by leeyongsuk** [comment]
지금있는곳이 고립망이라 개발환경을 구성하는데 어려움이 있어서 다음릴리즈때 확인해보겠습니다
확인감사합니다
