### ISSUE TITLE
Left 메뉴 Paper 설정에서 Clear All Paper 버튼에 Confirm 단계 추가.

### ISSUE THREAD

**Issue by gunlee01** [scouter-contrib/scouter-paper#134]
Left 메뉴 Paper 설정에서 Clear All Paper 버튼에 Confirm 단계 추가.

**Comment by kranian** [comment]
제가 해볼게요 ㅎㅎ

**Comment by kranian** [comment]
- 확인 버튼 아래 와 같이 했습니다.  
![image](https://user-images.githubusercontent.com/18545293/54017396-3aaa9300-41c9-11e9-9bac-5edabd8a0587.png)
