### ISSUE TITLE
Left 메뉴 API Sever 선택 영역에 Server명을 우선하여 http url과 함께 보여준다.

### ISSUE THREAD

**Issue by gunlee01** [scouter-contrib/scouter-paper#135]
## 요건 정의
좌측의 API SERVER 선택 메뉴에 현재 API의 주소가 나오고 있다.
여기에 `서버명(http:url)`로 보여주도록 개선한다.
(예) http://demo.scouterapm.com:6188

![image](https://user-images.githubusercontent.com/6788732/51084910-3e93d900-1775-11e9-9594-4d23083eb1d6.png)

## 개발 참고 사항
- 참고 또는 작업할 소스 : https://github.com/scouter-contrib/scouter-paper/blob/c7302c815a2a9f6ada6f94b18f630d0919635e05/src/components/Controller/Controller.js#L35

- 먼저 SimpleSelector 부분 참고 : https://github.com/scouter-contrib/scouter-paper/blob/c7302c815a2a9f6ada6f94b18f630d0919635e05/src/components/Controller/Controller.js#L845

- Server 정보(Server 이름) 획득
  - 각 Server로 `/scouter/v1/info/server` API를 호출하여 획득할 수 있다.
     - 참고 : https://github.com/scouter-contrib/scouter-paper/blob/c7302c815a2a9f6ada6f94b18f630d0919635e05/src/components/Controller/Controller.js#L482
  - 최초 화면에 진입시 Server들을 가져와서 세팅한다.
    - config에는 여러개의 API server를 등록할 수 있는데 이는 config.servers로 참조할 수 있다.
    - 각 server들로 위 API요청(`/scouter/v1/info/server`)을 보낸다.
    - 응답은 배열인데 화면에 보여줄 서버명은 배열 첫번째 항목의 name 값을 사용한다.

**Comment by kranian** [comment]
- 개발 시작해서 수정 했습니다. 
![image](https://user-images.githubusercontent.com/18545293/54064245-e4376600-4255-11e9-8bdf-a3090c389f4b.png)

- PR 요청 할게요 ^^
