### ISSUE TITLE
최종 선택되었던 object 들이 브라우저를 재 실행하여도 reset 되지 않고 그대로 존재하도록 한다.

### ISSUE THREAD

**Issue by gunlee01** [scouter-contrib/scouter-paper#136]
최종 선택되었던 object 들이 브라우저를 재 실행하여도 reset 되지 않고 그대로 존재하도록 한다.

**Comment by uuuusssseeeerrrr** [comment]
이거 해보려고 하는데요..
localstorage나 cookie 둘 중 하나써도되나요?
거기에 obj 넣고 빼면 될것같아서요.

**Comment by gunlee01** [comment]
설정등을 저장하기위해서 localstorage를 사용하고 있으니 동일하게 local storage를 사용하는 방식으로 처리하는게 좋을것 같네요

**Comment by uuuusssseeeerrrr** [comment]
질문이 하나 더 있습니다.
"선택한 오브젝트를 기억하여 로드"에 선택된 페이지(TOPOLOGY, PAPER)로의 페이지 이동도 포함되나요?
즉, 마지막 닫기직전의 URL을 그대로 저장해놨다가 로드해야되는건지요.
