### ISSUE TITLE
현재 사용중인 Preset과 Layout을 알 수 있도록 상단에 표기한다.

### ISSUE THREAD

**Issue by gunlee01** [scouter-contrib/scouter-paper#137]
현재 사용중인 Preset과 Layout을 알 수 있도록 상단에 표기한다.

**Comment by gunlee01** [comment]
# 요건정의
현재 선택된 Layout과 Preset의 명칭을 화면에 표시하여 준다.
모니터링 화면에서 어떤 시스템을 모니터링 중인지 바로 확인하기 어려운데
보통 Preset은 시스템 명을 나타내는 경우가 많으므로 이를 표시하여 모니터링 시스템을 명확히 알 수 있도록 한다.

![image](https://user-images.githubusercontent.com/6788732/51321965-82554e00-1aa7-11e9-934c-864633374db2.png)

**Comment by makkaba** [comment]
제가 한번 해보겠습니다

**Comment by gunlee01** [comment]
넵. 진행 부탁드립니다.
