### ISSUE TITLE
Url에 Preset을 포함하며, Url link로 object list외에 preset으로도 object들을 로드하여 보여줄 수 있게 한다.

### ISSUE THREAD

**Issue by gunlee01** [scouter-contrib/scouter-paper#138]
Url에 Preset을 포함하며, Url link로 object list외에 preset으로도 object들을 로드하여 보여줄 수 있게 한다.

**Comment by gunlee01** [comment]
# 요건정의
url에 preset 파라미터를 추가한다.
preset 파라미터에 값이 존재한다면 objHashes 파라미터는 무시하고 preset을 통해 오브젝트 목록을 로드하여 보여주도록 한다. 
 * 현재는 objHashes 파라미터에 콤마(,)로 연결된 objHash값이 들어오고 이 목록에 대한 성능 정보를 가져와 보여주는 기능만 제공된다.

**Comment by kyungseop** [comment]
@gunlee01 위의 일감을 가져가서 처리 하려면 여기서 말씀드리면 되나요?

**Comment by gunlee01** [comment]
네. 진행해주시면 됩니다.

**Comment by gunlee01** [comment]
@kyungseop 
컨트리뷰톤 기간이 종료 되었으니 이 이슈는 공개 이슈로 전환하겠습니다.

**Comment by gunlee01** [comment]
done
