### ISSUE TITLE
XLog 목록 테이블에서 스크롤시 헤더가 보이도록 고정한다.

### ISSUE THREAD

**Issue by gunlee01** [scouter-contrib/scouter-paper#139]
XLog 목록 테이블에서 스크롤시 헤더가 보이도록 고정한다.

**Comment by gunlee01** [comment]
# 요건정의
XLog 목록을 아래로 스크롤시 헤더가 감추어지는데, 헤더를 고정하여 스크롤시에도 보이도록 한다.
![image](https://user-images.githubusercontent.com/6788732/51322499-f3493580-1aa8-11e9-97ed-fcb9489966d1.png)

**Comment by mindplates** [comment]
헤더와 컨텐츠 부분을 분리하고, 컨텐츠 부분이 스크롤되도록 변경하거나, 혹은 적절한 테이블 컴포넌트로 아예 교체하는 것도 좋을 것이라 생각합니다.

**Comment by Ta2Rim** [comment]
제가 on-going중인 이슈 작업이 현재 불가능 하여 이 이슈 먼저 처리하도록 하겠습니다.

**Comment by Ta2Rim** [comment]
PR 올려놓았습니다.
거절될 경우 재작업 필요합니다.

**Comment by gunlee01** [comment]
네네. 수고하셨습니다. :)
PR 통해서 피드백 예정입니다.
지금 몇가지 작업 등등이 있어서 리뷰는 좀 지연 될 수도 있습니다.
