### ISSUE TITLE
XLog 목록 테이블에 헤더로 정렬하는 기능 추가

### ISSUE THREAD

**Issue by gunlee01** [scouter-contrib/scouter-paper#140]
XLog 목록 테이블에 헤더로 정렬하는 기능 추가

**Comment by gunlee01** [comment]
# 요건 정의
XLog 목록 테이블에서 헤더로 정렬하는 기능을 추가한다.
![image](https://user-images.githubusercontent.com/6788732/51322578-255a9780-1aa9-11e9-8817-c301a149a7b1.png)

**Comment by david100gom** [comment]
해당 이슈 제가 진행하겠습니다.
