### ISSUE TITLE
토폴로지에서 다른 메뉴로 이동하고 돌아오는 경우 토폴로지 위치, 설정을 기억하여 그대로 재현한다.

### ISSUE THREAD

**Issue by gunlee01** [scouter-contrib/scouter-paper#141]
토폴로지에서 다른 메뉴로 이동하고 돌아오는 경우 토폴로지 위치를 기억하여 그대로 재현한다.

**Comment by mindplates** [comment]
토폴로지의 데이터의 이동은 <Topology> 컴포넌트의 ticked() 메소드에서 처리되며, 현재는 위치를 기록하고, 초기 세팅을하는 부분이 존재하지 않아, 컴포넌트가 마운트될때 simulation에 의해서 위치가 새로 세팅되고 있다. 이 부분을 ticks() 메소드가 동작할때 동작 정보를 로컬 스토리지 등에 기록해두고, 이 후 토폴로지가 마운트되어 그려지는 update() 메소드에서 저장된 좌표 정보를 세팅해주는 방식으로 처리할 수 있을 것으로 생각된다.

**Comment by June-Young** [comment]
제가 확인하겠습니다
