### ISSUE TITLE
토폴로지의 요소들을 그룹화 하는 기능 (외부 연동, DB, Redis, Kafka, RabbitMQ등)

### ISSUE THREAD

**Issue by gunlee01** [scouter-contrib/scouter-paper#142]
토폴로지의 요소들을 그룹화 하는 기능 (외부 연동, DB, Redis, Kafka, RabbitMQ등)
위 요소들의 종류별로 System(WAS instances)당 하나만 존재하도록 그루핑하여 하나의 그래프로 연결한다.

**Comment by gunlee01** [comment]
### 아래 의견은 구상중인 내용이니 추가/변경/의견 제시 부탁드립니다.

* 현재 토폴로지 메뉴 "Grouping" 버튼 토글시 Application(javaee)가 그루핑 된다.
* 이를 All / Group Application / Group All 세 단계로 구분한다.
* Group All 선택시
  - 어플리케이션(javaee) 그룹에 각 연관 노드를 종류별로 하나씩만 연결한다.
     - 예를 들어 5개의 DB / 3개의 REDIS와 연동한다고 하더라고 이를 종류별로 그루핑 하여 하나로 묶어 연결한다.
     - 단 동일한 DB/REDIS를 연동한다고 하더라도 각 어플리케이션 그룹별로는 별개로 연결하도록 한다.
         - 각각 노드를 가져야 한다. (가시성을 위함)

### 즉 아래 그림처럼 표현한다. 
![image](https://user-images.githubusercontent.com/6788732/54082028-8d638680-4352-11e9-9cf3-baa72333342a.png)

**Comment by gunlee01** [comment]
위 그림에서는 항목 아래에 각각의 명칭을 나타냈는데 이게 많아지면 표현이 어려울 것 같으므로 
그냥 각 Redis, DB, External 항목을 그루핑하고 연동된 수량을 표시해 주면 좋을 것 같습니다.
( `10 targets` 처럼 표현하면 어떨까요? )

![image](https://user-images.githubusercontent.com/6788732/56864571-f1273900-69fe-11e9-9e91-14e7f4d9db26.png)

### 위 이미지는 그루핑이 선택되면 이런 식으로 표현이 될겁니다. (클라이언트도 여러개인 경우 동일하게 그루핑)
![image](https://user-images.githubusercontent.com/6788732/56864582-1320bb80-69ff-11e9-9f65-71e9e5f3b7f6.png)

그림에서 보다시피 동일한 DB에 접속해도 WAS 기준으로 별개로 보여집니다.

**Comment by gunlee01** [comment]
### 여기서 각 그루핑에 특정 액션을 하면 상세 정보가 보여져야 하는데요
어떻게 보여줄지는 아래 그림 참고만 하고 실제 개발하면서 자연스러운 방식으로 표시해 주면 좋을 것 같습니다.

![image](https://user-images.githubusercontent.com/6788732/56864610-73aff880-69ff-11e9-8181-832d907eabc1.png)

![image](https://user-images.githubusercontent.com/6788732/56864612-7a3e7000-69ff-11e9-8665-d584842ca165.png)

**Comment by kranian** [comment]
2.5.1에 반영 되었습니다. 이슈 종료 합니다.
