### ISSUE TITLE
XLog에서 0초 부근이 잘 보이도록 적용

### ISSUE THREAD

**Issue by gunlee01** [scouter-contrib/scouter-paper#143]
0초 부근의 XLog의 가시성 개선.

**Comment by gunlee01** [comment]
XLog의 0초 부근의 X모양의 점의 절반이 '0' 라인에 걸치게 되어 X 표시의 반만 보여진다.
이때문에 드래그로 선택이 어려운 단점이 있으며 이를 개선한다.

**Comment by Ta2Rim** [comment]
이슈 확인해보았는데요, 
0초 부근 데이터들이 더 잘보인다고 해도 드래그가 안되는 근본적 문제를 해결할 수 없을 것 같다는 생각이 들어서 차라리 xLog 드래그 시에 profiler창 위에

![image](https://user-images.githubusercontent.com/41318449/54487828-e21c7980-48dd-11e9-9dd9-836d702022c6.png)

이런느낌으로 
현재 선택한 y축 range에 대해 보여주고, 변경이 가능하게 하는 UI를 추가하는 방법을 생각해 보았는데요,
이렇게 하면  0부근과 최상단 부근 데이터도 설정이 쉬워지게 됩니다.



의견 부탁드립니다.

**Comment by gunlee01** [comment]
아직 구체화 하지 않은 이슈인데 이렇게 의견 주셔서 감사합니다.

제 생각으로는 이런 방법은 어떨까 합니다.

1. 먼저 X로그가 잘 보이지 않는 것
  - 0초 라인을 중심으로하여 십자가(혹은 엑스)를 그리지 않고, 0초 라인을 베이스로 하여 XLOG를 그리는 방법
       예를 들어 다른 XLOG 화면을 보면 0초가 걸린 XLOG가 0초를 베이스라인으로 하여 그려지고 있습니다.
![image](https://user-images.githubusercontent.com/6788732/54499872-07e76400-495a-11e9-8365-9575d40cda67.png)
  - 특히 에러인 경우 시인성을 좋게하기 위해 보통 붉은색으로 표현이 되는데 에러는 0초로 바로 튕겨나가는 경우가 많기 때문에 더 잘 안보이는 것 같네요.
  - 문제는 이렇게 하는 경우 상한쪽에 걸리는 XLOG는 TOP라인을 기준으로 그려줘야 제대로 보일 것 같긴합니다.

2. 드래그가 잘 되지 않는 것
  - 이건 지금 다시해보니 어렵지 않게 선택이 되는군요. ^^;
     - 그래도 만약 좀더 개선해 보자면 사용자를 살짝 속이는 방법은 어떨까 합니다.
       예를 들면 선택 영역의 하한이 Y축 Max의 1/100이하라면 그냥 0으로 처리하는 겁니다.
        Y Max가 10초 일때는 0.1초 미만이 선택되면 그냥 0으로 처리하는 거죠. 
  - 그런데 이건 그냥 나둬도 될 것 같습니다. 다시 해봐도 0초짜리 XLOG도 선택이 잘 되는 것 같네요.

**Comment by kranian** [comment]
X 로그를 잘 보이는 하는 방법에 대해 개인적인 의견을 내봅니다. 

# 첫번째
응답 시간 구간별 베이스 라인이 있으면 어떻까요? 그리고 에 베이스 라인을 조절 해서 보는 것입니다
베이스 라인 구간은 아래 예처럼 옵션 처리 하구요. 설정에 따라서  Y축 응답 시간을 변경 하는거죠 
  - 0 ~ 1초
 -  1초 ~ 5초 
 -  5초 ~ 10초 
 -  10초 이상 

# 두번째
사용자가 XLog 차트에 마우스로  줌인, 줌아웃 기능이 있으면 좋겠네요, 그려면 내가 원하는 구간을 줌인 해서 
보는거니깐 편하지 않을까요??

다른 방법으로는 사용자가 보고 싶은 구간만 드래그 에서 모달로 띄어서 보는게 있으면 편할것 같아요 
구체적으로 설명 하자면  내가 보고자 하는 구간을 드래그 하면  해당 구간을 기준으로 모달로 XLog 차트를 띄어서 보는 거에요. 그려면 사용자는 해당 트랜잭션만 집중 해서 볼수 있을것 같습니다. 

# 세번째 
XLog 차트에 얼마 정도 트랜잭션이 카운트가 찍히는지 있는지가 없어 불편 하더군용 . 우측 상단에 트랜잭션 Count가 추가 됐음 좋겠어요 

이 의견은 XLog 볼때 분석 관점에서 어떻게 하면 편하게 보고 분석할수 있을까 생각 해 본거에요

**Comment by gunlee01** [comment]
### 첫번째
말씀하신 내용이 잘 이해가 되지는 않는데요. 
Y축 응답시간 변경은 XLOG의 Y축 조정은 차트 Y축에 있는 +/- 로 조정이 가능한데
이 기능이면 비슷하게 사용할 수 있지 않을가요?

### 두번째 말씀해 주신것
고려해 본 내용이고 언젠가는 적용할 기능이긴 한데 우선 순위가 높지는 않은 기능입니다. 
Scouter의 전용 클라이언트에 들어간 기능인데 실제 실무에서 활용도가 별로 높지 않더라고요.
아래 그림 처럼 Shift 키와 함께 드래그하면 Zoom된 결과 창이 탭으로 하나 더 열립니다.
![image](https://user-images.githubusercontent.com/6788732/54506872-fca82e80-4981-11e9-9d79-bf03da7e8c52.png)


### 세번째
XLOG의 카운터 기능은 아주 좋은 아이디어 같습니다. 실제 모니터링시 도움도 많이 됩니다.
  `Error/All : 112(붉은색) / 12,353`
  - 그리고 Filter를 걸면 Filter가 걸린 결과가 반영되어서 숫자가 표현 되어야겠죠.

**Comment by kranian** [comment]
첫번째 사항은 Y축을 설정을 상세하게 못봐서 놓쳤던 부분 이네요 
제가 말하는 Y축 베이스 라인을 넣어 보는건 아래 처럼 넣으면 어떻까 생각해 본거에요 ^^
![image](https://user-images.githubusercontent.com/18545293/54507493-01221680-4985-11e9-90d8-8e3888c69953.png)

XLog 분포도에 구간 별 라인이 있으면 라인 기준으로 응답 시간 분포도의 성능이 나쁜지 좋은지 판별이 쉬게 되지 않을까? 하고 생각해 봤어요

**Comment by gunlee01** [comment]
일단 이 이슈가 너무 복잡해지니
이 이슈에서는 요건 Scope을 **XLog가 0초 혹은 Max에 걸려 절반만 보이는 것**을 개선하는 것으로 정리하겠습니다.
나머지 제안들은 이후에 추가적인 이슈로 처리하겠습니다.

XLog 건수를 보여주는 부분은 추가 이슈로 바로 등록하겠습니다.

**Comment by kranian** [comment]
XLog Class 모드를 추가하면서  0초 부분은 찍은 부분을 그리는 부분을 위로 , Max는 바로 아래노 보이게끔 개선 했습니다. 

- XLog Current 
![image](https://user-images.githubusercontent.com/18545293/69008422-af0b1800-098d-11ea-8e27-47f076d8ae34.png)

- XLog Class Mode
![image](https://user-images.githubusercontent.com/18545293/69008437-d06c0400-098d-11ea-8e0d-7e76f40f4138.png)

해당 부분은 2.6.2 릴리스에 반영될 예정입니다. 그럼 수고하세요
