### ISSUE TITLE
XLog 프로파일 뷰의 상단에 SQL / API Call / OTHERS의 수행 시간 비율을 시각화 하여 표현

### ISSUE THREAD

**Issue by gunlee01** [scouter-contrib/scouter-paper#144]
XLog 프로파일 뷰의 상단에 SQL / AI / OTHERS의 수행 시간 비율을 시각화 하여 표현

**Comment by gunlee01** [comment]
# 요건 정의
프로파일 뷰의 가시성을 개선하기 위해
불필요한 정보를 삭제하고 각 요소별 응답시간을 가로 막대 형태로 표현한다.

상단의 테이블에선 Service, IP, End Time, Error만 보여주고 
각 시간 정보는 프로파일 시간축의 위나 아래에 가시성있게 배치하도록 한다.
각 CPU Time, SQL Time, API Time, Others로 나누어 시간 비율에 맞도록 각각의 고유 색으로 표현한다.

![image](https://user-images.githubusercontent.com/6788732/51323388-6c498c80-1aab-11e9-9567-8d1ba059411c.png)

**Comment by voyagerwoo** [comment]
이건 제가 해보겠습니다.

**Comment by gunlee01** [comment]
넵~ 부탁드립니다

**Comment by voyagerwoo** [comment]
현재 테이블을 정리하고 바 형태로 시간비율을 보여주는 부분까지는 구현을 했습니다.
그런데 cpu, sql, api  시간이 없는 경우가 많아 테스트하기가 좀 어려운데요, 혹시 좋은 테스트 상황이 있을까요?

![image](https://user-images.githubusercontent.com/1849824/54076176-cae0f900-42eb-11e9-828e-93b0e7b3fb1c.png)

https://github.com/voyagerwoo/scouter-paper/commit/67fd81a3dd4ece539ea2e25b58983faa76f6f0f6

**Comment by voyagerwoo** [comment]
제가 임의로 퍼센트를 입력했을때 화면은 이렇습니다.

![image](https://user-images.githubusercontent.com/1849824/54076252-e8629280-42ec-11e9-85da-b6ee2fc111ff.png)

**Comment by gunlee01** [comment]
네. 감사합니다.

API, SQL 들이 다 있는게 URL이 별로 없군요. (샘플 시스템이라 요청 상황이 그리 다양하지가 않습니다.)
/traceability/cross-service/simple 여기 좀 나올 것 같긴합니다.

그리고 SQL, API, CPU, OTHER 라고 박스 안에 표현해 주면 더 좋을 것 같습니다.
일단 여기까지 하고 Pull Request 하시면
나머지는 리뷰과정에서 추가 코멘트 될 거니 PR 올려주시면 됩니다.

**Comment by voyagerwoo** [comment]
https://github.com/scouter-contrib/scouter-paper/pull/166 
PR 올렸습니다. 확인 부탁드립니다. 어떤 리뷰도 달게 받겠습니다! :smile

**Comment by gunlee01** [comment]
초기 구상보다 고려할 것이 많은 듯 하여 POINT를 변경하였습니다.
