### ISSUE TITLE
에러메시지 창 개선

### ISSUE THREAD

**Issue by gunlee01** [scouter-contrib/scouter-paper#145]
# 요건 정의
API 호출시 응답에러에 대해 사용자에게 적극적으로 알리지 않도록 개선한다.
간헐적인 응답 문제 발생시 사용성이 저하되며, 지속적으로 발생시 모달 창으로 인해 특정 오퍼레이션이 불가능해 지기도 한다.
 - scouter web API 호출에 대한 에러 발생시 에러 메시지 창을 사용자에게 직접적으로 띠워주지 않는다.
    - 에러메시지를 직접 띠워주지 않고 console에 error로 기록합니다.
    - Local Storage에 최근 20개를 저장합니다.

**Comment by david100gom** [comment]
해당 이슈 제가 진행해 보겠습니다.

**Comment by gunlee01** [comment]
네 부탁드립니다.
