### ISSUE TITLE
페이퍼 메뉴로 들어가는 경우 라인차트의 데이터를 초기 로딩하지 않는 옵션을 추가한다.

### ISSUE THREAD

**Issue by gunlee01** [scouter-contrib/scouter-paper#146]
# 요건 정의
초기 진입시 Paper가 많은 화면인 경우 초기 로딩이 오래 걸리고 또한 초기 로딩 시간동안 리얼타임을 조회하지 않기 때문에 차트가 끊겨 보이게 된다.
  - Scouter 클라이언트처럼 초기 로딩하지 않는 옵션을 추가한다.(Setting에 추가)
  - 옵션이 ON 인 경우는 라인 차트의 과거 10분 데이터를 로드하지 않는다.
  - 추가로 각 Paper에 Refresh 아이콘이 존재하고 이를 클릭하면 해당 차트의 데이터를 지우고 다시 과거 10분데이터를 다시 로드하여 표현해 준다.

![image](https://user-images.githubusercontent.com/6788732/51323830-9f405000-1aac-11e9-9f1e-6400508d4c20.png)

**Comment by mindplates** [comment]
<Settings>에 옵션을 추가하기 위해서는 reducers/index.js의 configState에 항목을 먼저 추가합니다. 다른 항목들을 참조하여 옵션을 추가했다면, 사용자가 해당 값을 변경할 수 있게되며, 이 후 해당 값에 따라서 초기 로딩하지 않도록 로직을 수정합니다. 데이터를 로드하는 로직은 <Paper>에 포함되어 있습니다.

**Comment by david100gom** [comment]
해당 이슈  제가 진행하겠습니다.

**Comment by gunlee01** [comment]
네. 부탁드려요.
