### ISSUE TITLE
토폴로지의 각 요소 CPU 상태에 따른 색상 변화 처리

### ISSUE THREAD

**Issue by gunlee01** [scouter-contrib/scouter-paper#147]
토폴로지의 각 요소 CPU상태에 따른 색상 변화 처리

**Comment by mindplates** [comment]
토폴로지는 <Topology> 컴포넌트를 통해서 작성되어 있으며, 조회한 데이터를 가공하여, update() 메소드를 통해 차트를 업데이트한다. 이때 update() 내부에서 노드, 노드의 텍스트, 노드간의 연결선 등이 d3의 selection과 enter(), exit(), update 패턴으로 작성되어 있으므로, CPU 상태에 따라 변경하려고하는 부분의 색상을 데이터에 맞게 설정하면 된다.

**Comment by Ta2Rim** [comment]
이슈 제가 담당하겠습니다.

**Comment by gunlee01** [comment]
네 부탁드려요~

**Comment by Ta2Rim** [comment]
@gunlee01 
![image](https://user-images.githubusercontent.com/41318449/54073704-cad20080-42cd-11e9-8209-1521d3c8bbb3.png)

색상변화가 되어야하는 부분이 정확히 어디인지 설명해주실 수 있으신가요?
이슈를 보고 각 노드 색상을 변경하면 될거라고 생각했는데
각 요소에는 이미 해당되는 대표 색상이 입혀져있어서 수정이 불가능해보이네요.

**Comment by gunlee01** [comment]
각 오브젝트 (혹은 그루핑 선택시 오브젝트의 그룹)의 Host 들의 CPU 값을 기준으로,
현재 바탕이 흰색인 부분에 색상을 입히는 것(혹은 해당 색상이 깜밖 거리는 것)을 고려하였습니다.
(방법은 배경색상? 혹은 해당 색상의 투명도가 있는 원을 위에 덮는다던지 등...)
더 좋은 방법이 있으시다면 제안해 주셔도 좋을 듯 합니다.

CPU가 70% 이상이라면 옐로우 계열의 색상
90%이상이라면 레드 계열의 색상을 표현하면 어떨까 합니다.
(그룹이라면 해당 그룹의 Host 중에 하나라도 이 수치를 넘는 경우 색상이 표현되면 좋을 것 같습니다.)

현재 조회 결과에 CPU가 포함되어 있지 않은데 이를 포함하는 패치가 금일 적용 예정입니다.
패치 후에 여기에 댓글로 알려드리겠습니다.

**Comment by gunlee01** [comment]
토폴로지 데이터를 표현해주는 Interaction Counter 요청에 CPU 정보가 포함되었습니다.
결과는 아래 형식으로 포함되니 참고하세요.
```javascript
{
  "status": "200",
  "requestId": "#gif126",
  "resultCode": "0",
  "message": "success",
  "result": [
    {
      "objName": "/sc-api-demo-m01.localdomain/sampleweb",
      "interactionType": "INTR_API_INCOMING",
      "fromObjHash": "-1502713930",
      "fromObjName": "/sc-api-demo-s01.localdomain/sampleweb",
      "fromObjCounters": [
        {
          "name": "Cpu",
          "value": "3.9338465"
        },
        {
          "name": "ActiveSpeed",
          "value": [
            "4",
            "0",
            "0"
          ]
        }
      ],
      "toObjHash": "-1180057655",
      "toObjName": "/sc-api-demo-m01.localdomain/sampleweb",
      "toObjCounters": [
        {
          "name": "Cpu",
          "value": "10.256601"
        },
        {
          "name": "ActiveSpeed",
          "value": [
            "2",
            "0",
            "0"
          ]
        }
      ],
      "period": "30",
      "count": "2",
      "errorCount": "0",
      "totalElapsed": "6"
    },
...
```

**Comment by Ta2Rim** [comment]
이부분은 작업내용과 무관한게 궁금한 것인데요
![image](https://user-images.githubusercontent.com/41318449/54211046-f4846500-4523-11e9-9594-8ff31e58d72c.png)
왜 instance에서 가져오는것과 아닌것을 따로 분기하는 건지 궁금합니다.
캐싱하는 소스인가요?

**Comment by Ta2Rim** [comment]
생각보다 UX에 대한 고민도 들어가고 구조 파악도 필요하여
꼭 제가 처리하지 않더라도
good for 1st contriution 라벨 삭제와 포인트 상향조정을 검토 부탁드립니다.

**Comment by Ta2Rim** [comment]
DEFAULT, WARNING, IN_DANGER 3개로 분기,
WARNING인 경우 4초마다 깜빡임 , IN_DANGER 인 경우 2초마다 깜빡임 애니메이션을 추가하였습니다.

깜빡임 애니메이션을 추가한 이유는 현재 노드마다 아이콘 - border색상이 지정되어있는데
상태변화 색과 비슷한 계열 색상일 경우 아이콘이 전혀 보이지 않게 되어서 내린 결정입니다.

**Comment by gunlee01** [comment]
@Ta2Rim 의견 감사합니다. ^^
의견 주신대로 저희가 초반 생각한 것보다 고려해야 많은 것 같습니다.
레벨 조정하였습니다.

**Comment by gunlee01** [comment]
> 이부분은 작업내용과 무관한게 궁금한 것인데요
> ![image](https://user-images.githubusercontent.com/41318449/54211046-f4846500-4523-11e9-9594-8ff31e58d72c.png)
> 왜 instance에서 가져오는것과 아닌것을 따로 분기하는 건지 궁금합니다.
> 캐싱하는 소스인가요?

이 부분만 봐서는 잘 모르겠는데... 
일단 instance에 type 정보가 없으면 일단 임의의 타입 정보를 만들어 넣어주고
한번 넣으면 그 값을 그냥 사용하는 로직 같긴한데요. 매번 연산할 필요는 없으니 한번만 하겠네요.
@mindplates 님 맞나요?

**Comment by mindplates** [comment]
@Ta2Rim 위의 코드 부분은 실제 조회된 topology 데이터에 해당하는 instances 데이터를 찾는 과정에서 topology 데이터에는 있는데, instances에 해당 정보가 없는 경우를 처리하기 위한 코드입니다.
예를 들어, topology 데이터에 from 데이터의 노드를 인스턴스에서 찾을 수 없고, 해당 데이터가 NORMAL_INCOMING하면, from을 클라이언트로 결정하기 위한 코드입니다.
즉, 스카우터에서 식별되는 노드들 이외의 클라이언트나, kafka, rabbitMQ 부분을 정황을 토대로 특정 노드로 식별하기 위함입니다.
