### ISSUE TITLE
차트 타입에 Stack Type 추가

### ISSUE THREAD

**Issue by gunlee01** [scouter-contrib/scouter-paper#148]
* 차트 타입에 Stack Type 추가
  - 차트에서 보여주는 계열 중에 해당 시간에 비어있는 데이터를 어떻게 처리할지에 대한 고민 필요 
     차트가 깨지지 않으면 될 듯.
  - 스택차트에서 툴팁을 표현할때는 **SUM(합계) 에 대한 정보**도 들어가야 한다.
  - 스택차트인 경우 차트당 하나의 메트릭만 허용하여야 한다.
  - (Option) 스택차트에 추가 옵션(혹은 다른 차트 유형 옵션-SUM 차트?)을 통해 SUM 만 표현해 주는 옵션이 있는 건 어떨지? 

-----
* 아래 이슈는 다른 이슈로 이관 예정이므로 이 이슈에서 제외한다.
    - 차트 타입에 대칭 차트 추가
       - 예를 들면 Network IN Bytes Counter는 Y축 (+) 영역에
       - Network OUT Bytes Counter는 Y축 (-) 영역으로 선택하여 표시할 수 있는 차트

**Comment by mindplates** [comment]
우선 <Paper>에 렌더링되는 차트들에는 설정 버튼이 우측에 표시되며, 차트의 종류에 따라 각각의 설정 정보가 다르다. 이러한 설정 정보는 PaperControl/Options.js에 정의되어 있으며, 해당 파일에 각 차트별로 가지는 옵션의 정보와 옵션을 사용자가 변경할 수 있는 컨트롤을 제공하기 위한 메타 정보를 가지고 있다. 다만 현재 LineChart(혹은 counter)의 경우에는 별도의 설정 정보가 없으며, counter는 다른 차트들고 달리 웹 API에서 내려주는 목록을 기반으로 PaperControl을 만든다. 따라서 기존의 정보와는 조금 다른 형태로 Options 처리를 해야하는데, 우선 Options.js에 counter의 키를 만들고, 추가할 옵션(여기서는 차트의 형태, Fill 여부 등)을 적절하게 추가하고, <PaperControl>에서 서버로부터 가져온 목록을 렌더링할때 data 속성에 정의한 counter가 포함되도록 설정한다. 그러면 사용자가 추가한 매트릭에 정의한 설정 정보가 적용되고, 사용자가 값을 변경할 수 있다.

이렇게 정의된 속성은 <LineChart>에서 꺼내서 사용할 수 있게되며, 이러한 속성 값에 따라 Stack, Fill 등의 차트 옵션이 동작하도록 <LineChart>를 변경하면 된다.

Line, Area, Fill 등의 차트 구현은 d3 예제등을 살펴보면 어렵지 않게 구현할 수 있으며, Fill 부분은 <Settings>의 옵션을 통해 이미 코드 상으로 구현되어 있으므로, 전체 옵션과 함께 새로 정의한 차트 개별 옵션을 통해 동작하도록 간단히 수정가능하다. area 차트의 경우에는 현재 데이터 특성이 line으로 되어 있으므로, stack 형태의 데이터로 변환하여 그래프 작성 코드를 분기하도록 한다.

**Comment by gunlee01** [comment]
done
