### ISSUE TITLE
실시간서비스목록 1. Active service 이퀄라이저 클릭시 실시간 서비스 목록 화면 오버레이 기능

### ISSUE THREAD

**Issue by gunlee01** [scouter-contrib/scouter-paper#151]
실시간서비스목록 1. Active service 이퀄라이저 클릭시 실시간 서비스 목록 화면 오버레이 기능

**Comment by mindplates** [comment]
실시간 서비스 정보는 <ActiveSpeed> 컴포넌트에 작성되어 있으며, 서버로 부터 가져온 카운트 정보를 DOM을 이용하여 가로 막대 그래프 형태로 보여주고 있습니다. 실시간 서비스 목록 화면 오버레이 기능이라는 것은 서버별로 보여지는 카운트 정보에 해당하는 서비스 목록을 팝업 형태로 보여주는 기능을 구현하는 것을 의미합니다.

먼저 render에서 this.props.objects를 통해 반복하여 실시간 서비스 정보를 출력하는 row에 클릭 이벤트를 처리하고, 이벤트 파라미터로 object의 id를 받아서, 스카우터 WEB API 서버에 현재 서비스를 조회하는 이벤트를 처리합니다.

서버로부터 데이터를 처리는 <Paper> 컴포넌트에서 이루어지며, 현재 ActiveSpeed의 데이터는 <Paper> 컴포넌트의 getRealTimeCounter() 메소드를 통해 가져옵니다. 다만 구현하려는 서비스 목록은 사용자의 클릭 이벤트에 따라 처리되어야하므로, getRealTimeCounter()와는 별도로 처리하는 메소드를 추가하고, 수신된 데이터를 앞으로 추가할 컴포넌트로 전달하기 위한 데이터 구조로 저장해두어야 합니다.

실시간 서비스 목록 조회를 위한 API는 @gunlee01 님이 추가적으로 작성해주실 것입니다.

이렇게 서버로부터 클릭한 서비스에 대한 목록 정보를 수신했다면, 수신된 데이터를 출력할 컴포넌트를 작성해야합니다. XLOG 차트에서 사용자가 드래그했을 경우 나타나는 목록과 같은 형태로 만든다고 가정할 경우에는 <Paper> 컴포넌트의 자식 컴포넌트로 작성하는 것이 좋습니다. XLOG 차트의 상세 정보는 <Paper>컴포넌트 하위에 <Profiler>로 작성되어 있습니다.

이후 처리해야하는 내용은 서버로 부터 조회된 데이터의 특성이나, 실제 구현하는 화면에 따라 다르겠지만, <Profiler>와 유사한 형태라면, 해당 컴포넌트를 참조하는 것도 괜찮다고 생각합니다.

**Comment by kranian** [comment]
이거는 제가 한번 해보겠습니다 ㅎㅎ

**Comment by gunlee01** [comment]
실시간 서비스 목록 조회 API 스펙이 필요하실때 말씀해주시면 제공해드리겠습니다.

**Comment by gunlee01** [comment]
* 실시간 서비스 목록인 이런식으로 조회가 가능합니다.
http://127.0.0.1:6188/scouter/v1/activeService/ofObject/-1180057655

/v1/activeService/ofObject/{objHash}

* 응답 샘플
```javascript
{
	"status": "200",
	"requestId": "#7cm2",
	"resultCode": "0",
	"message": "success",
	"result": [
		{
			"objHash": "-1180057655",
			"objName": "/sc-api-demo-m01.localdomain/sampleweb",
			"threadId": "37",
			"threadName": "http-nio-8080-exec-4",
			"threadStatus": "TIMED_WAITING",
			"threadCpuTime": "5287800",
			"txidName": "z2qine3t2p9al0",
			"elapsed": "1225",
			"serviceName": "/simulate/type/seconds-delay<GET>",
			"ipaddr": "127.0.0.1",
			"note": null,
			"mode": "NONE"
		},
		{
			"objHash": "-1180057655",
			"objName": "/sc-api-demo-m01.localdomain/sampleweb",
			"threadId": "4229502",
			"threadName": "http-nio-8080-exec-15",
			"threadStatus": "TIMED_WAITING",
			"threadCpuTime": "1736750",
			"txidName": "x1nju9sa22bgdq",
			"elapsed": "327",
			"serviceName": "/simulate/type/millis-delay<GET>",
			"ipaddr": "127.0.0.1",
			"note": null,
			"mode": "NONE"
		}
	]
}
```

**Comment by gunlee01** [comment]
SCOUTER 클라이언트에서는 이렇게 표시됩니다.
참고하세요.
아래 그림 좌측의 Active Service 이퀄라이저를 클릭하면
현재 시점 서버에서 수행중인 요청 목록이 보여지게 됩니다. 
색상은 elapsed가 각 3초 이상 7초 이상인 경우 yellow, red로 나타납니다.
![image](https://user-images.githubusercontent.com/6788732/54066193-80219b80-426f-11e9-8941-85ddd30569df.png)

우측에는 리프레시 버튼이 있고 이를 누르면 동일 조건으로 다시 서버로 요청된 결과로 갱신합니다.
![image](https://user-images.githubusercontent.com/6788732/54066377-2cfd1800-4272-11e9-962f-f74d00a2a5e1.png)

**Comment by kranian** [comment]
액티브 대상을 클릭하면 조회가 되는 api가 같이 알여주시겠어요 ㅎㅎ ???

확인 하고 같이 할수 있으면 개발 해 보도록 하겠습니다

**Comment by kranian** [comment]
아 잘못 말해 군요 스택 트레이스 조회 api는 없나요?

**Comment by gunlee01** [comment]
/v1/activeService/thread/5289166/ofObject/-1180057655
/v1/activeService/thread/{threadId}/ofObject/{objHash}
이 API 입니다.
위에서 조회된 결과에 있는 threadId 가 추가로 파라미터로 전달됩니다.

**Comment by gunlee01** [comment]
Scouter 클라이언트에서는 이런 형식으로 보여줍니다.

![image](https://user-images.githubusercontent.com/6788732/54067148-d0085e80-427f-11e9-9eea-4020bb1d193b.png)

**Comment by gunlee01** [comment]
이 이슈는 따로 분리되어 있습니다. 

https://github.com/scouter-contrib/scouter-paper/issues/152

**Comment by kranian** [comment]
아하 그렇군요 알겠습니다

**Comment by kranian** [comment]
- 말쓴 해주신 가이드 대로 구현 해봤습니다. 
![image](https://user-images.githubusercontent.com/18545293/54075107-869b2c00-42de-11e9-9373-421e3d738c53.png)

-  문의사항은 액티브 스피드를 클릭한 시점의 스레드 개수 와  조회 결과가 다른니다. 개인적인 이문제는 WAS와 수집 서버 간의 시간차로 느껴지는데 맞나요??

**Comment by kranian** [comment]
액티브 서비스 Row를 클릭하면 스택 트레이스( #152)가 오른쪽에서  나오면 좋을것 같은데요. #151 이슈 검토 해주시고 말씀해 주세요.  지금 이슈 검토 끝나면 #152도 제가 같이 진행 해도 될까요?

**Comment by gunlee01** [comment]
@kranian ㅎㅎ 네네
#151은 요건 구현되었으니 PR 주시면 될 듯 합니다.

#152는 저희도 구상할때 우측에 나오는 걸로 생각했습니다.
연관 건이라 같이 진행해 주시면 좋을 것 같습니다. 👍
