### ISSUE TITLE
실시간서비스목록 2. 실시간 서비스 목록에서 하나의 row(서비스) 선택시 상세 내용 화면

### ISSUE THREAD

**Issue by gunlee01** [scouter-contrib/scouter-paper#152]
실시간서비스목록 2. 실시간 서비스 목록에서 하나의 row(서비스) 선택시 상세 내용 화면

**Comment by mindplates** [comment]
실시간 목록을 가져오기 위한 매커니즘과 동일한 형태로 데이터를 송/수신합니다. 사용자가 클릭한 목록의 키를 서버로 전달하여, 데이터를 조회하고, 해당 데이터의 특성에 맞게 상세 영역의 컴포넌트를 작성합니다.

하나의 서비스의 데이터 제공하는 API는 @gunlee01 님이 추가적으로 작성해주실 것 입니다.

데이터를 보고 판단해야 정확하겠지만, 일반적으로 현재 서비스(혹은 쓰레드)의 정보에는 현재 동작중인 코드의 스택 정보와, 쓰레드의 상태 값, 시간이나 메모리 등의 숫자 값들이 포함되어 있을 것 입니다.
즉, 키/밸류 형태의 값들의 반복과, 특정 범위내의 목록 (Thread State 등)과 스택 정보로 나눌 수 있을 것이며, 이 중 스택 정보 등은 가능하다면 별도의 beautifier 컴포넌트를 찾아서 사용하는 것이 좋을 것이라고 판단되며, 혹은 적절한 컴포넌트를 찾지 못한다면, 현재 <Profiler> 컴포넌트에서 SQL를 출력하기 위해 사용하고 있는 ace editor를 이용하는 것도 한 방법일 수 있다고 생각합니다.

**Comment by gunlee01** [comment]
* API
/v1/activeService/thread/5289166/ofObject/-1180057655
/v1/activeService/thread/{threadId}/ofObject/{objHash}

**Comment by gunlee01** [comment]
Scouter 클라이언트에서는 이런 형식으로 보여줍니다.

![image](https://user-images.githubusercontent.com/6788732/54067148-d0085e80-427f-11e9-9eea-4020bb1d193b.png)

**Comment by kranian** [comment]
문의 사항 입니다. 진행 하고 있는데 액티브 서비스 조회 결과 하고 스택 트레이스 내용하고 매칭 안됩니다. 
스택 트레이스의 서비스 이름 과 조회 목록 하고 매칭이 안돼네요 ..

![image](https://user-images.githubusercontent.com/18545293/54096032-660dc780-43ed-11e9-8220-bdcf4b0d09ea.png)

이유는 조회 목록 시점 하고 WAS상에 실행 하고 있는 액티브 스레드 스택 트레이스 하고 타임 갭 문제인걸로 예상이 되는데 맞나요???  

타임 갭으로 인한 문제라면 개인적인 의견으로는 조회 시도를 했을 경우 스택 스택트레이스만 오른쪽 화면에서 full로 노출 되었으면 좋겠습니다. 그리고 다시 조회 화면이으로 이동시에는 상단 위 버튼을 눌려서 이동 할수 있도록 했으면 좋겠어요

**Comment by gunlee01** [comment]
네 클릭 시점의 정보라 맞지가 않겠네요.
보통 이런 기능을 제공하는 다른 APM에서는 상세 스택정보를 팝업으로 처리하는지라 이상하게 생각되지는 않는데
이 UI에서는 사용자가 볼 때 이상해 보일 것 같습니다.
어떤식으로 풀지 좀 고민이 필요할 듯 한데 

일단 이 이슈는 이대로 진행해주시고
더 좋은 방법은 고민해보고 다른 개선 이슈로 추진하도록 하겠습니다.

**Comment by kranian** [comment]
@gunlee01 네 알겠습니다. 
현재 개발이 완료 돼서 PR 해서 올리도록 하겠습니다.

**Comment by kranian** [comment]
![image](https://user-images.githubusercontent.com/18545293/54102730-f8719380-440c-11e9-9e9b-0f601414a2b0.png)
 - 스택 트레이스 갱신 버튼 과 액티브 서비스 조회 화면으로 이동할수 있는 버튼을 추가 했습니다. 
    - 스택 트레이스 갱신 버튼은 애틱브 서비스 하나의 ROW(서비스) 만 선택시에만 활성화 됩니다.
