### ISSUE TITLE
XLog 필터 후 드래그 선택시 404 에러 발생

### ISSUE THREAD

**Issue by gunlee01** [scouter-contrib/scouter-paper#153]
XLog 필터 후 드래그 선택시 404 에러 발생. 아주 미세하게 잘 선택하면 된다.
- 필터링되 비어있는 영역의 xlog 부터 카운팅해서 그런게 아닌지 의심됨.

**Comment by kranian** [comment]
해당 이슈에 대해서 재현 해 봤습니다. 스카우터 APM 데모 서버로 주소를 설정했고, 트랜잭션 필터 설정은 
address 에 127.0.0.1 로 했습니다. 

- 필터 전 
![image](https://user-images.githubusercontent.com/18545293/54324898-f42ebb80-4642-11e9-9365-dd735ae3e9fc.png)


- 필터 후 
![image](https://user-images.githubusercontent.com/18545293/54324794-81254500-4642-11e9-97b2-85f1340eac34.png)
 - 필터 전에 트랜잭션 점들이 있는 구간에 마우스를 드레그 해봤는데 404 에러가 발생 하더군요.

**Comment by kranian** [comment]
확인 결과 필터링 있는 비어있는 영역의 xlog 부터 카운팅해서 발생함 문제 입니다. 
수정 했어요. PR 할게요

**Comment by gunlee01** [comment]
:+1:
