### ISSUE TITLE
Paper 접속 시 파란 화면만 나옵니다.

### ISSUE THREAD

**Issue by moonkoo88** [scouter-contrib/scouter-paper#154]
PC, android 에서 접속 시 이상 없는데 ios 에서 접속 시 파란 화면만 나옵니다.

**Comment by gunlee01** [comment]
음.. safari 가 아마 제대로 안 나올 수 있을텐데요, 크롬으로 접속해 보세요.
크롬을 사용했는데 그런거라면 일단 시크릿탭으로 한번 해보시기 바랍니다.
쿠키나 로컬스토리지에 잘못된 정보가 있어서 그럴수도 있을 것 같습니다.

자세한건 아마 @mindplates 께서 답변을 해주실 듯..

**Comment by moonkoo88** [comment]
답변 감사드립니다.
ios 환경에서 알려주신대로 다른 브라우저 이용해 보았는데 동일 증상 발생하고 있습니다.
크롬, 파이어폭스, 웨일 등 (시크릿 탭 사용)

mac os 에서는 사파리는 화면이 깨지는 현상이 보입니다. (크롬에서는 정상 작동)

현상 캡처 하여 첨부 드립니다.

<img width="1680" alt="kakaotalk_20190226_223644666" src="https://user-images.githubusercontent.com/37525955/53416701-5d91b600-3a17-11e9-9091-dc274a0403b8.png">
![kakaotalk_20190226_222427862](https://user-images.githubusercontent.com/37525955/53416724-697d7800-3a17-11e9-9bab-e64e1e8eb221.jpg)

**Comment by mindplates** [comment]
@moonkoo88 
제가 해당 이슈를 놓쳐서 이제 봤습니다~ 혹시 해결되셨나요?
아직 동일 증상이시라면,  혹시 파란화면만 나올때,
개발자 도구로 한번 콘솔에 오류가 없는지, 혹시 있다면 어떤 메세지가 있는지 알려주시겠어요? 
개발자 도구의 콘솔과 네트워크 탭을 확인해주셔서 특이사항이 있는 메세지가 있는지 스샷 부탁드리겠습니다.

**Comment by moonkoo88** [comment]
@mindplates 
안녕하세요 
아직 해결 못하였습니다.
IOS 브라우저 개발자 도구 스샷 첨부 드립니다.
감사합니다!!

![1](https://user-images.githubusercontent.com/37525955/54122456-6be0c880-4440-11e9-94ff-f37b870cff56.png)
![KakaoTalk_20190311_204852747](https://user-images.githubusercontent.com/37525955/54122517-9763b300-4440-11e9-82bb-7d7d46bcf5f4.png)
![KakaoTalk_20190311_204852729](https://user-images.githubusercontent.com/37525955/54122536-a21e4800-4440-11e9-8686-45f02976f684.png)

**Comment by moonkoo88** [comment]
@mindplates

안녕하세요.
문제 되는 ios 환경에서 특이사항 메시지 스샷 첨부 드렸었는데요.
혹시 제가 설정을 잘못해서 그런것인지 아니면 다음 릴리즈 때 수정되는 부분인지 알 수 있을까요?
일단 현재는 PC 또는 Android 기기에서 사용하고 있습니다.
계속 요청만 드려 죄송합니다 ㅠㅠ

**Comment by mindplates** [comment]
다음 릴리즈에 반영될 예정입니다. 고생하셨습니다!
