### ISSUE TITLE
UX 개선 건의 - 신규 접속시 서버 연결이 되지 않음 에러 메세지 삭제

### ISSUE THREAD

**Issue by Ta2Rim** [scouter-contrib/scouter-paper#157]
이슈를 수정하기 위해 신규로 접속을 시도했는데요,
https://github.com/scouter-contrib/paper-contributhon/blob/master/contributhon/preparing-development.md
에도 나와있다시피 제일 처음 접속시에 서버가 설정되어있지 않은것이 당연한데, 

![image](https://user-images.githubusercontent.com/41318449/54073172-54320480-42c7-11e9-89c1-16e53927c12c.png)

사용자가 이렇게 에러메세지를 보게 되는데요, 물론 설명으로 대체가 가능한 부분이지만 
사용자에게 서버 설정이 잘못된것이나 혹은 버그로 인식될 수도 있을 것 같습니다.

제가 생각한 UX는 2가지가 있습니다
첫번째난 설정한 내역이 없는경우 setting페이지로 리다이렉트 시켜주는 것이고, 두번째는 에러메시지의 내용을 설정내역이 없다는것으로 대체하는 것입니다.
 혹은 더 좋은 방법이 있다면 대체하는 것이 좋아보입니다.

**Comment by gunlee01** [comment]
@Ta2Rim 좋은 제안감사합니다.
그런데 신규 접속 여부를 판단하기가 애매할 수 있을듯 합니다.
최초 접속시 127.0.0.1 6188이 기본 설정으로 제공되기 때문입니다.
(그리고 URL 링크로 들어오면 자동으로 서버와 Preset, Layout이 세팅되기도 합니다.)

* 예를 들어 아래 링크로 열면 만약 해당 서버 세팅이 되어 있지 않다면 url에 있는 서버가 세팅에 등록이 됩니다.
  * http://demo.scouterapm.com:6188/extweb/index.html#/paper?address=demo.scouterapm.com&port=6188&realtime=false&xlogElapsedTime=8000&instances=-796172661,1139150454,-1180057655,1463674242,-1502713930,-30645576&from=20190310080800&to=20190310081800&layout=Only-Web-Dashboard&longterm=false&objects=1463674242,-1180057655,-30645576,-1502713930,1139150454,-796172661

그러나 일반적으로 실시간 모니터링 시스템에서 이런 식(전체 팝업)으로 에러를 표현하는 것은 저희도 좋은 방법이 아니라고 판단하여 생성한 이슈가 하나 있습니다.

해당 이슈 보시고 괜찮으시다면 진행해 주시면 좋을 듯 합니다.
 - https://github.com/scouter-contrib/scouter-paper/issues/145

**Comment by Ta2Rim** [comment]
대체 이슈가 존재하여 이슈 close하였습니다.
