### ISSUE TITLE
다른 메뉴로 이동 후 토폴로지로 돌아온 경우 기존 배치를 그대로 유지한다.

### ISSUE THREAD

**Issue by gunlee01** [scouter-contrib/scouter-paper#159]
# 요건 정의
다른 메뉴로 이동후 토폴로지로 돌아오면 기존에 배치한 모양이 변경되어 있다.
이를 그대로 유지하도록 한다. (기존 토폴로지에 존재하지 않다가 추가된 인스턴스등은 자동으로 배치)
또한 브라우저를 닫고 다시 들어온 경우에도 유지한다.

**Comment by Ta2Rim** [comment]
'기존 토폴로지에 존재하지 않다가 추가된 인스턴스' 상황이 발생하는 경우가
사이드바에서 control 설정을 변경한 경우 맞나요? 
다른경우도 있다면 작업자가 놓치지 않게 적어주시면 좋을 것 같습니다!

**Comment by gunlee01** [comment]
맞습니다. Paper뷰에서 모니터링시에 대상 인스턴스 선택을 변경할 수 있는데 토폴로지 이동시 동일한 인스턴스들을 대상으로 토폴로지를 표현합니다.
만약 메뉴 이동후 돌아오면 이전에 사용자가 배치한 토폴로지 위치를 그대로 보여준다고 한다면,  추가되거나 대상에서 빠진 인스턴스들이 있을텐데요 이 상황을 말씀드린겁니다.
