### ISSUE TITLE
토폴로지 기본 옵션 변경

### ISSUE THREAD

**Issue by gunlee01** [scouter-contrib/scouter-paper#160]
# 요건 정의
현재 토폴로지의 기본 옵션을 다음과 같이 변경한다. 
 * GROUPING - ON
 * TPS ON LINE SPEED - FAST
 * HIGHLIGHT - ON
 * PIN - ON

**Comment by david100gom** [comment]
혹시 해결된 이슈인가요?

**Comment by gunlee01** [comment]
@kyungseop 님이 진행중이신 듯 한데 아직 PR이 올라오지 않아서 대기 중입니다.

**Comment by idess** [comment]
PR #177 번으로 소스 커밋되어 있습니다. development branch에서 바뀐 것을 확인할 수 있습니다.

**Comment by gunlee01** [comment]
네. 제가 착각했네요 ;)
