### ISSUE TITLE
PAPER 조회시 시간 범위 선택 방법 개선

### ISSUE THREAD

**Issue by gunlee01** [scouter-contrib/scouter-paper#161]
# 요건 정의
현재 Seach의 경우 시간 범위를 특정 시간을 선택 후 해당 시간으로 부터 얼마 기간을 조회할 지를 세팅한다.
일반적으로 현재 시점에서 과거로 조회를 하는 경향이 많으므로 이를 아래 첨부된 그림과 같이 개선한다.

![image](https://user-images.githubusercontent.com/6788732/54082309-acfcae00-4356-11e9-930f-c7838041340b.png)

**Comment by Ta2Rim** [comment]
제가 이슈 담당하겠습니다.

**Comment by Ta2Rim** [comment]
@mindplates 
현재 relatime과 search 메뉴를 오갈 때
`this.props.range.realTime` 이라는 boolean변수를 이용하고 있는데요
이슈 변경사항에 따르면 1개의 상태값이 더 추가되게 됩니다.

처음 개발 방향은 this.props.range.realTime 에 해당 value를
objRangeValues = {
        'REALTIME' : 1,
        'RELATIVE' : 2,
        'ABSOLUTE' : 3
    };
로 한정하여 상태를 한가지 더 추가하는 것이었는데요,

코드를 확인해보니 this.props.range.realTime를 사용하는 곳이 굉장히 많더라구요 (reducer 코드도 변경 필요)
그래서 boolean 값 2개로 운용을 ( realTime, isAbsolute) 하는게 맞는지,
공수가 크더라도 this.props.range.realTime 을 enum-like하게 운용하는게 맞는지 궁금합니다.

 제가 섣불리 고치기 전에 확인을 받는게 좋을거 같아서 코멘트 달았습니다.

**Comment by gunlee01** [comment]
@mindplate께서 의견을 주시겠지만
저도 좀 생각을 해봤는데요, 
제 생각으로는 영향도가 크다면 
realTime(Boolean)과 다른 속성을 하나 더 추가하는 건 어떨까 합니다.
의미상으로도
* real time
* not real time
  - relative
  - absolute
로 생각하면 이상할 것 같지는 않습니다.
그리고 relative / absolute는 검색조건 UI에서 사용자가 Range를 편하게 선택하기 위한 옵션일 뿐이므로
별개로 생각해도 무방하지 않을까요?

**Comment by gunlee01** [comment]
@Ta2Rim님. 혹시 이 이슈 계속 진행하실 예정이신가요?

**Comment by gunlee01** [comment]
DONE
