### ISSUE TITLE
Object 선택창에 및 필터창에서 InActive Object는 글자색을 회색으로 표시

### ISSUE THREAD

**Issue by gunlee01** [scouter-contrib/scouter-paper#162]
Active/InActive 여부는 /v1/object 요청의 결과로 알 수 있다.

```javascript
{
  "status": "200",
  "requestId": "#gif9479",
  "resultCode": "0",
  "message": "success",
  "result": [
    {
      "objType": "reqproc",
      "objFamily": "reqproc",
      "objHash": "-388472869",
      "objName": "/sc-api-demo-s02.localdomain/sampleweb/http-nio-8080",
      "address": "172.31.21.206",
      "version": "",
      "alive": true,
      "lastWakeUpTime": "1552205350635",
      "tags": {
        "counter": "11099"
      }
    },
    {
      "objType": "reqproc",
      "objFamily": "reqproc",
      "objHash": "28163508",
      "objName": "/sc-api-demo-s01.localdomain/another-web/http-nio-8081",
      "address": "172.31.31.84",
      "version": "",
      "alive": true,
      "lastWakeUpTime": "1552205350879",
      "tags": {
        "counter": "13160"
      }
    },...
```
### Object 선택창
![image](https://user-images.githubusercontent.com/6788732/54082340-68254700-4357-11e9-8eb5-196c3edc2853.png)

### Object 필터창
![image](https://user-images.githubusercontent.com/6788732/54082359-c3573980-4357-11e9-8893-eeee88e44aa2.png)

**Comment by kranian** [comment]
분석 해서 확인 해 보니깐 paper control 컴포넌트가 한번 만 object 정보가 들어와 있네요. 그려면 이안에 alive 정보도 같이 들어가 있습니다. 그 이후에 objects의 갱신은 신경 않써도 되나요 ^^?

**Comment by kranian** [comment]
현재 paper control 컴포넌트에서 최종 한번 objects 정보에 alive 정보가 있어서 회색으로 바꿔봤어요 ^^

**Comment by gunlee01** [comment]
@kranian 
아무래도 inactive object는 주기적으로 혹은 특정 사용자 action 시에 갱신이 되면 좋을 것 같습니다.
- object필터/선택창을 누르는 경우에 갱신하거나
- 또는 그냥 30초 단위 정도의 주기로 갱신하거나

**Comment by kranian** [comment]
첫번째가 좋을것 같네요 
object필터/선택창을 누르는 이벤트 발생시 갱신 하는게 좋으것 같아요

**Comment by kranian** [comment]
수정  해서 PR 했습니다. ^^ 검토 부탁 드려요 ~~~~
