### ISSUE TITLE
버그 - Loading UI 스크롤 하단 적용되지 않는 이슈

### ISSUE THREAD

**Issue by Ta2Rim** [scouter-contrib/scouter-paper#165]
![image](https://user-images.githubusercontent.com/41318449/54082612-e4ba2480-435b-11e9-92c5-37f91bee8256.png)

스크롤이 있는 페이지의 경우 로딩창이 나오고 있을 때 하단으로 스크롤이 가능하고,
스크롤 할 경우 Loading UI가 적용되지 않은 부분이 보입니다.

로딩시에는 스크롤 을 불가능하게 하거나
로딩 UI 높이를 document 전체로 수정해야 할 것 같습니다.

**Comment by gunlee01** [comment]
네. 제안 감사합니다.
컨트리뷰톤 대상 이슈로 추가하도록 할게요.

**Comment by kranian** [comment]
확인해서 보니깐 innerLoading 콤포넌트 와 css 속성이 중복이 돼서 지금 같은 현상이 발생 했네요 
innerLoading css의 네임 스페이를 변경 해서 수정 했습니다. PR 할게요 ^^
