### ISSUE TITLE
source map 옵션 

### ISSUE THREAD

**Issue by makkaba** [scouter-contrib/scouter-paper#172]
웹팩의 source map 옵션에 따라서 
빌드 시 원본 소스와 맵핑되는 정도와 번들 파일의 크기 등이 바뀌게 됩니다 [(참고)](https://github.com/webpack/webpack/tree/master/examples/source-map)

현재 설정
```
devtool: 'cheap-module-source-map'
```
현재 설정으로는 원본 소스를 보기가 힘들어 디버깅에 어려움이 있는 것 같습니다
production, development 모드를 나누고   
모드에 따라 source-map 옵션을 다르게 하면 어떨지 이슈를 제기해봅니다.

참고)
https://webpack.js.org/configuration/devtool/
http://cheng.logdown.com/posts/2016/03/25/679045
https://survivejs.com/webpack/building/source-maps/

**Comment by gunlee01** [comment]
간단한 이슈인데 바로 진행하면 좋을것 갵은데요?

**Comment by gunlee01** [comment]
inline-source-map과 hidden-source-map 정도로 하면 어떨까요?

**Comment by idess** [comment]
development branch에서 webpack.config.dev.js는 'inline-source-map'로 등록되었네요.
따라서, webpack.config.prod.js에서 'hidden-source-map'으로 변경하겠습니다.
