### ISSUE TITLE
XLog.js TypeError: Cannot read property 'parentNode' of undefined 

### ISSUE THREAD

**Issue by kyungseop** [scouter-contrib/scouter-paper#175]
1. 서버설정 
 - PROTOCOL: HTTP
 - ADDRESS: demo.scouterapm.com 
 - PORT: 6188
 - AUTHENTIFICATION TYPE: N/A 
2. CONTROL > TARGET OBJECT 설정 (172.31.21.150 HOST-ScouterDemo)
3. CHANGE LAYOUT 에러 LAYOUT 변경 시 TypeError 발생
4. 재연되는 경우 
 -  CHANGE LAYOUT 에 있는 목록을 1초 간격으로 클릭하여 변경 시 바로 발생
 -  CHANGE LAYOUT 에 있는 목록을 1초 간격으로 변경 후 다른탭으로 이동 (PAGER CONFIG)
  - PAPER CONFIG 에서 CLEAR ALL PAPER 클릭 후 ADD PAPER 로 빈페이지 생성 후 CONTROL 탭으로 이동

<img width="905" alt="settings" src="https://user-images.githubusercontent.com/2485456/54472795-fd21b780-4811-11e9-9a43-c36160f66134.png">

<img width="641" alt="xlog_error" src="https://user-images.githubusercontent.com/2485456/54472797-001ca800-4812-11e9-80c3-5256e100e193.png">

<img width="1100" alt="error_text" src="https://user-images.githubusercontent.com/2485456/54472828-81743a80-4812-11e9-9ae7-2c646254d59c.png">

**Comment by idess** [comment]
해당 이슈는 layout를 선택할 때 마다 LayoutManger에서 선택된 template의 box를 state에 저장하고 불러오는 과정에서 완전히 render되지 않았거나 unmount가 되어버렸는데 resizeTimer가 동작하여 this.refs.xlogViewer를 select해서 발생되는 오류 입니다.
따라서, resizeTimer가 this.refs.xlogViewer를 select할 때 undefined이면 처리할 필요가 없으므로 if로 분기하는 로직을 추가하였습니다.
