### ISSUE TITLE
XLog 차트에 건수 표시

### ISSUE THREAD

**Issue by gunlee01** [scouter-contrib/scouter-paper#178]
XLOG 차트에 건수를 표시해준다. (상단 헤더에 표시하면 될 듯)
 - 전체 건수와 에러 건수를 표시한다.
 - 예를 들어 아래와 같이 표시할 수 있다.
    - `Error/All : 112 / 12,353`   <-- 112는 에러 건수이므로 강조되는 계열의 색상으로 표시한다.
- 필터를 적용한 경우에는 필터된 건수만 표시되어야 한다.

**Comment by koamania** [comment]
이슈 담당하겠습니다

**Comment by koamania** [comment]
![image](https://user-images.githubusercontent.com/11426944/55004245-38479600-501d-11e9-85e3-067e418f8d52.png)

말씀하시는 헤더가 xlog 타이틀이 나오는 부분을 말씀하시는거라면 거기보다는 그래프 우 상단에 위치하도록 하는게 더 좋아보이는게 어떠신가요

**Comment by gunlee01** [comment]
네 좋아보이네요

**Comment by gunlee01** [comment]
@koamania 
컨트리뷰톤 기간이 종료 되었으니 이 이슈는 공개 이슈로 전환하겠습니다.

**Comment by June-Young** [comment]
공개이슈로 전환되어 pull request 드렸습니다
확인부탁드립니다

**Comment by gunlee01** [comment]
DONE
