### ISSUE TITLE
XLog 차트 Y축 Scale 변경시 및 Layout 변경시 URL에 반영

### ISSUE THREAD

**Issue by gunlee01** [scouter-contrib/scouter-paper#181]
* XLog 차트의 (+) (-) 버튼으로 Y축 Scale 변경시 URL에 반영한다.
   - URL 주소로 Share 할 때 해당 설정이 같이 반영되도록 함.
     - 예) `http://url......&xlogElapsedTime=3000`

* Layout 변경시 URL에 반영
   - 예) `http://url......&layout=xxxxx`

**Comment by idess** [comment]
제가 작업을 진행하겠습니다.
궁금한 사항이 있습니다. 혹시 layout의 값으로 template의 name 혹은 no 중 뭘로 반영할까요?
layout=xxxxx로 표기하셔서 이름일 것 같아서 작업했는데, no라면 수정 가능합니다.

**Comment by gunlee01** [comment]
layout 이름이 맞습니다.   :)

**Comment by gunlee01** [comment]
링크를 복사해서 크롬 시크릿탭을 열고
붙여넣었을때 xlog 높이와 layout이 그대로 나오면 됩니다.
