### ISSUE TITLE
XLog 필터 항목 추가

### ISSUE THREAD

**Issue by gunlee01** [scouter-contrib/scouter-paper#182]
### 현재 XLog 필터에 제공되지 않는 필터를 추가로 개발한다.
![image](https://user-images.githubusercontent.com/6788732/54863492-ac1f3f80-4d8c-11e9-9a19-537d4419f233.png)

* Text1, Text2, Text3, Text5, Text5
   * 사용자 정의 확장 값으로 사전을 사용하지 않는 일반 문자열 값이다.
   * XLog의 text1 ~ text5

* Profile Size ( X ~ Y 의 범위로 검색) : 값이 없으면 X=0, Y는 무한대이다.
   * XLog의 profileCount

* Start Time 
  * endTime - elapsed : 시분초의 범위로 검색 (예: 13:50:10 ~ 13:50:15)

* Has Dump Y/N 
  * hasDump 가 1인 xlog

**Comment by david100gom** [comment]
해당 이슈 제가 진행해 보겠습니다.

**Comment by gunlee01** [comment]
네. 부탁드립니다 ^^

**Comment by david100gom** [comment]
@gunlee01 XLog Response 데이터중에 profileCount 가 없는것 같습니다. 제가 놓친것이 있는지 코멘트 부탁드립니다.

![image](https://user-images.githubusercontent.com/13757297/55370899-18d9cd00-5537-11e9-8ffd-99144cf24d3c.png)

**Comment by gunlee01** [comment]
저녁쯤에 확인해보고 필요하면 demo server update 해놓도록 하겠습니다.

**Comment by gunlee01** [comment]
이제 profileCount 나오니 다시 한번 확인해보세요.
