### ISSUE TITLE
Papers 화면  LineChart 생성 시 TypeError 발생

### ISSUE THREAD

**Issue by kyungseop** [scouter-contrib/scouter-paper#186]
Target objects 선택 후 Papers 탭으로 이동시  TypeError 발생
- xlog 를 제외한 Layout 추가 시 화면에서 에러 발생

<img width="402" alt="Paper-objects" src="https://user-images.githubusercontent.com/2485456/55336483-f4023d00-54d7-11e9-8faf-0ad44c62a8ec.png">

<img width="571" alt="Paper-layout" src="https://user-images.githubusercontent.com/2485456/55336484-f4023d00-54d7-11e9-981b-e530ee08640a.png">

<img width="1030" alt="Paper-error" src="https://user-images.githubusercontent.com/2485456/55336490-f5cc0080-54d7-11e9-88c6-27c127292663.png">

d3 라이브러리 관련 dependency 오류일 수도 있어서 yarn.lock 파일도 함께 첨부

**Comment by kyungseop** [comment]
[yarn-lock.txt](https://github.com/scouter-contrib/scouter-paper/files/3030015/yarn-lock.txt)

**Comment by kranian** [comment]
- 탭 이동 간 순간적으로 발생 하는 현상입니다. 
- 에러 발생 원인 아래와 같습니다. 
   - Paper 데이터 로딩 => 시계열 차트 200ms 후 렌더링  => 시계열 차트 렌더링 전 사용자가 바로 Option 탭 이동 시=> 시계열 차트 렌더링 이벤트 실행 
      -  의견) 사라진 위치에다 렌더링 시도를 하기 때문에 위와 같은 에러 발생 하는 걸로 보이네요 
- 이 부분의 해결 방안은 어떻게 하는게 좋을지 고민을 해봐겠습니다.

**Comment by kranian** [comment]
기존 d3 조작 방법을 time delay 방식에서 React 이벤트 방식으로 변경 해  해당 문제 해결 했습니다. 
해당 문제 수정은 2.5.0 이후  릴리스에 적용될거에요

**Comment by kranian** [comment]
2.6.0 에 반영되었습니다.
