### ISSUE TITLE
xlog 드래그시에 목록에 더블로 표현됨.

### ISSUE THREAD

**Issue by gunlee01** [scouter-contrib/scouter-paper#192]
xlog 두개 선택한 화면.
4개의 ROW로 보이며, ROW를 클릭하면 두 row가 선택된다.
![image](https://user-images.githubusercontent.com/6788732/56006869-88a73f00-5d11-11e9-8b53-27a416cbb6b2.png)

**Comment by uuuusssseeeerrrr** [comment]
제가 진행해볼게요.

**Comment by uuuusssseeeerrrr** [comment]
이거 혹시 저렇게 발생하는 특정한 조건이 있나요? development branch에서 발생하는 현상 맞지 않나요? 저는 아무리 해도 정상적으로 떠서요..

**Comment by gunlee01** [comment]
실제 동일 데이터가 먼저 두개가 존재하게 되는 현상인 것 같습니다.
잘 재현이 되지 않고 있네요. 원인 파악되는데로 업데이트 하겠습니다.
