### ISSUE TITLE
XLOG 데이터 노출 문제.

### ISSUE THREAD

**Issue by david100gom** [scouter-contrib/scouter-paper#193]
- 특정 상황에서 XLOG 데이터가 10분전 데이터가 아닌 현재 시점의 데이터부터 노출되며, 이 상태에서 그래프의 크기를 조절하면 10분전 데이터가 다시 나타나는 현상이 발생.
[재연] 
   1. PAPERS 메뉴에서 다른 그래프를 다 삭제하고 XLOG 만 남긴다.
   2. TOPOLOGY 메뉴와   PAPERS 메뉴를 번갈아 클릭한다.
   3. 기타 - SETTING 메뉴에 추가된 DATA PRELOAD (Y/N) 기능과 상관없이 발생.

[정상 로드된 화면]
![image](https://user-images.githubusercontent.com/13757297/56263879-a0bafc00-611f-11e9-89ba-d946af64d7d9.png)

[비정상 로드된 화면]
![image](https://user-images.githubusercontent.com/13757297/56263859-884ae180-611f-11e9-915f-39e5df4c2823.png)

**Comment by kranian** [comment]
#확인 결과  
  - TOPOLOGY 메뉴와 PAPERS 메뉴를 번갈아 클릭시 기존 X-LOG 데이터가 화면상에 보이지 않는 현상임

**Comment by kranian** [comment]
TOPOLOGY 메뉴와 PAPERS 메뉴를 번갈아 클릭시 차트 리사이즈 이벤트가 발생 하면서 차트를 초기화 하여 이전에 그린 데이터가 보이지 않는 현상 발생
