### ISSUE TITLE
GRAY 테마에서 너무 글자가 보이지 않습니다. 

### ISSUE THREAD

**Issue by cowboy93** [scouter-contrib/scouter-paper#201]
![image](https://user-images.githubusercontent.com/175918/58079011-056be980-7beb-11e9-80f4-9defe278b2a4.png)

XLog 를 긁어서 분석할 때 상단에 있는 항목별 시간 그래프에 글자가 안보입니다. :) 

개선이 필요해 보입니다.

**Comment by cowboy93** [comment]
XLog 의 점이 파란색이다보니 점도 잘 안보입니다 ^^

**Comment by kranian** [comment]
![image](https://user-images.githubusercontent.com/18545293/59656704-60d4cb80-91d9-11e9-8778-b3c7f4a7ac85.png)

확인 해 보니. 상단 부분에 테마 설정이 안들어 있네요. Gray 테마에 잘 보도록 컬러 설정을 변경 하겠습니다.

**Comment by kranian** [comment]
2.5.1에 릴리스 되어 이슈 종료 합니다.
