### ISSUE TITLE
XLog 목록에서 행 선택시 우측에 나타나는 프로파일 창의 스크롤 초기화

### ISSUE THREAD

**Issue by gunlee01** [scouter-contrib/scouter-paper#211]
* XLog 목록에서 행 선택시 우측에 나타나는 프로파일 창의 스크롤 초기화
   * 현재 선택시 스크롤이 맨위로 올라가지 않고 중간 어딘가에 나타나서 어색함.

**Comment by mindplates** [comment]
개발 브렌치에 적용되었으며, 다음 릴리즈에 반영될 예정입니다.
