### ISSUE TITLE
Paper 실시간 5분 옵션을 만들면 어떨지?

### ISSUE THREAD

**Issue by gunlee01** [scouter-contrib/scouter-paper#213]
인스턴스와 Paper가 많아지면 자원 사용량이 너무 높아짐
현재 리얼타임 10분으로 고정인데 세팅에 리얼타임 5분 설정을 하나 넣어 선택할 수 있게 하면 좋을 것 같음.

**Comment by kranian** [comment]
5분 옵션을 넣어도 동일한 현상이 존재 할 겁니다. 왜냐하면 시계열 차트가 다수 배치된 상태에서 인스턴스 개수가 증가하면 메모리 사용량이 (인스턴스 개수(10이상, * ( 시계열 차트5개이상 + 성능 카운터(20개) ))  개수만큼 증가하는 문제가 있습니다.

따라서 시계열 데이터와 현재 데이터를 적절히 배분하여 화면에 최적화된 방법을 제공을 하는게 가장 좋을 것 같고요

현재는 NOW()를 볼수 있는 차트가 없기 때문에  도넌 차트 나 카운터 차트(넘버 차트) ,바 차트 등을 추가해 주면서 최적화를 찾아야 하는게 맞을 것 습니다.

**Comment by gunlee01** [comment]
@kranian 그렇군요. 
CPU 부하가 높아서 기본 조회시간을 절반으로 줄이면 그려야할 xlog나 차트의 점들이 줄어드니 좀 나아지지 않을까 하고 그냥 단순하게 생각해 본 건입니다. ^^

**Comment by david100gom** [comment]
인스턴스 개수도 동일하다는 가정하에 실시간 조회가 10분에서 5분으로 줄어들면 로컬 PC CPU부하는 줄어들겠죠.
setting 쪽에 REALTIME DATA RANGE (minutes) 항목으로 추가해 놓고, 기본은 5분 그리고, 10분도 선택 가능하게 해주면 될것 같습니다.

**Comment by kranian** [comment]
- 현재 시간 관련 컨트롤러 입니다. 
![image](https://user-images.githubusercontent.com/18545293/60221846-2f818d00-98b6-11e9-9895-f075e3dc148c.png)

- 개선을 아래 예 처름 해보는건 어떨까요??
![image](https://user-images.githubusercontent.com/18545293/60221889-550e9680-98b6-11e9-874a-b069d3fa742b.png)
  - 리얼 시간 탭에 시간과 갱신 주기 설정을 사용자 입력을 받아 처리 하고, default  설정은 setting 탭에서 처리 합니다.

**Comment by david100gom** [comment]
@kranian 오~ 감사합니다. 우선 setting 부분에 넣고 나서, 제안주신 내용은 추후에 정리해 보겠습니다.

**Comment by kranian** [comment]
# 설정 화면 
![image](https://user-images.githubusercontent.com/18545293/69333636-68266680-0c9c-11ea-937d-589e91a3b395.png)
 - XLog, Counter 실시간 Last 가져오는 시간 개별로 설정 가능 하도록 설정 추가 
 - XLOG 시간 설정 범위, 1분 ~ 최대 120분
 - Counter 시간 설정 범위 , 1분 ~ 최대 10분 
# 결과 
![image](https://user-images.githubusercontent.com/18545293/69333325-cacb3280-0c9b-11ea-9d8f-1d6f065902ab.png)
