### ISSUE TITLE
필터링 후 URL을 복사하여 시크릿 창에서 실행하면 에러가 발생하고 페이퍼 화면이 사라진다.

### ISSUE THREAD

**Issue by gunlee01** [scouter-contrib/scouter-paper#214]
필터링 후 URL을 복사하여 시크릿 창에서 실행하면 에러가 발생하고 페이퍼 화면이 사라진다.

**Comment by gunlee01** [comment]
필터에 별표가 들어간 경우 에러가 발생하는 것 같음.

## 정상인 경우

http://demo.scouterapm.com:6188/extweb/index.html#/paper?objects=1463674242%2C1858489355%2C-1180057655%2C-30645576%2C2033927919%2C1291312847%2C911699808%2C1315531795%2C-1502713930%2C1139150454&layout=default&address=demo.scouterapm.com&port=6188&protocol=http&realtime=true&longterm=false&from=20190612230700&to=20190612231700&xlogfilter=%7B%22txid%22%3A%22%22%2C%22gxid%22%3A%22%22%2C%22type%22%3A%22ALL%22%2C%22minElapsedTime%22%3A%22%22%2C%22maxElapsedTime%22%3A%22%22%2C%22service%22%3A%22%2Fsimulate%2Ftype%2Fseconds-delay%3CGET%3E%22%2C%22referrer%22%3A%22%22%2C%22userAgent%22%3A%22%22%2C%22login%22%3A%22%22%2C%22desc%22%3A%22%22%2C%22address%22%3A%22%22%2C%22serviceMatcher%22%3A%7B%22comp%22%3A%22EQU%22%2C%22pattern%22%3A%22%2Fsimulate%2Ftype%2Fseconds-delay%3CGET%3E%22%2C%22mid%22%3A%22%2Fsimulate%2Ftype%2Fseconds-delay%3CGET%3E%22%7D%2C%22referrerMatcher%22%3A%7B%22comp%22%3A%22EQU%22%2C%22pattern%22%3A%22%22%2C%22mid%22%3A%22%22%7D%2C%22userAgentMatcher%22%3A%7B%22comp%22%3A%22EQU%22%2C%22pattern%22%3A%22%22%2C%22mid%22%3A%22%22%7D%2C%22loginMatcher%22%3A%7B%22comp%22%3A%22EQU%22%2C%22pattern%22%3A%22%22%2C%22mid%22%3A%22%22%7D%2C%22descMatcher%22%3A%7B%22comp%22%3A%22EQU%22%2C%22pattern%22%3A%22%22%2C%22mid%22%3A%22%22%7D%2C%22addressMatcher%22%3Anull%2C%22small%22%3Afalse%2C%22hasDump%22%3A%22ALL%22%2C%22startHmsFrom%22%3A%22%22%2C%22startHmsTo%22%3A%22%22%2C%22profileCountFrom%22%3A%22%22%2C%22profileCountTo%22%3A%22%22%2C%22text1%22%3A%22%22%2C%22text2%22%3A%22%22%2C%22text3%22%3A%22%22%2C%22text4%22%3A%22%22%2C%22text5%22%3A%22%22%2C%22filtering%22%3Atrue%7D

## 에러 발생하는 경우

http://demo.scouterapm.com:6188/extweb/index.html#/paper?objects=1463674242%2C1858489355%2C-1180057655%2C-30645576%2C2033927919%2C1291312847%2C911699808%2C1315531795%2C-1502713930%2C1139150454&layout=default&address=demo.scouterapm.com&port=6188&protocol=http&realtime=true&longterm=false&from=20190612230700&to=20190612231700&xlogfilter=%7B%22txid%22%3A%22%22%2C%22gxid%22%3A%22%22%2C%22type%22%3A%22ALL%22%2C%22minElapsedTime%22%3A%22%22%2C%22maxElapsedTime%22%3A%22%22%2C%22service%22%3A%22*seconds-delay*%22%2C%22referrer%22%3A%22%22%2C%22userAgent%22%3A%22%22%2C%22login%22%3A%22%22%2C%22desc%22%3A%22%22%2C%22address%22%3A%22%22%2C%22serviceMatcher%22%3A%7B%22comp%22%3A%22MID%22%2C%22pattern%22%3A%22*seconds-delay*%22%2C%22mid%22%3A%22seconds-delay%22%7D%2C%22referrerMatcher%22%3A%7B%22comp%22%3A%22EQU%22%2C%22pattern%22%3A%22%22%2C%22mid%22%3A%22%22%7D%2C%22userAgentMatcher%22%3A%7B%22comp%22%3A%22EQU%22%2C%22pattern%22%3A%22%22%2C%22mid%22%3A%22%22%7D%2C%22loginMatcher%22%3A%7B%22comp%22%3A%22EQU%22%2C%22pattern%22%3A%22%22%2C%22mid%22%3A%22%22%7D%2C%22descMatcher%22%3A%7B%22comp%22%3A%22EQU%22%2C%22pattern%22%3A%22%22%2C%22mid%22%3A%22%22%7D%2C%22addressMatcher%22%3Anull%2C%22small%22%3Afalse%2C%22hasDump%22%3A%22ALL%22%2C%22startHmsFrom%22%3A%22%22%2C%22startHmsTo%22%3A%22%22%2C%22profileCountFrom%22%3A%22%22%2C%22profileCountTo%22%3A%22%22%2C%22text1%22%3A%22%22%2C%22text2%22%3A%22%22%2C%22text3%22%3A%22%22%2C%22text4%22%3A%22%22%2C%22text5%22%3A%22%22%2C%22filtering%22%3Atrue%7D

**Comment by david100gom** [comment]
resolved
