### ISSUE TITLE
Profile에 대한 Topology 표현

### ISSUE THREAD

**Issue by gunlee01** [scouter-contrib/scouter-paper#218]
하나의 요청에 대해 서버간 호출관계(분산 트랜잭션 추적)를 나타내는 XLog 프로파일 창에 프로파일에 대한 Toplogy를 표현하여 준다. (클릭시 팝업? 탭? 등으로.)

![image](https://user-images.githubusercontent.com/6788732/59418180-8d689c00-8e03-11e9-982f-0fd7cff6912f.png)

**Comment by kranian** [comment]
탭 또는 Summay 내부에 구분 해서 보여 주는것도 괂찮을것 같습니다.

**Comment by kranian** [comment]
서버간 호출관계(분산 트랜잭션 추적)를 나타내는 API는 어떻게 호출 하면 되나요? 파라미터 값하고 API 주소을 알고 싶습니다.

**Comment by gunlee01** [comment]
gxid로 관련된 xlog를 모두 조회하는 api가 있습니다. (gxid는 모든 xlog에 포함되어 있으며 값이 없다면 txid=gxid 입니다.)
https://github.com/scouter-project/scouter/blob/master/scouter.webapp/src/main/java/scouterx/webapp/layer/controller/XLogDataController.java#L219

이 api로 기본적인 서비스간 연결정보의 구성이 가능할 듯 합니다.
 : xlog간 연결 정보 - txid, caller를 통해 알수 있음
 : 호출된 서비스명, 서비스 응답시간등

기본 정보외에 정보를 좀 더 많이 보여주시려고 한다면 profile API를 통해 각 상세 profile들을 조회해 와서 필요한 부분을 조합 해야 합니다. 이러면 구현은 좀 복잡해지긴 합니다.
(예를 들어 프로파일 스텝에 포함된 정보를 사용하고자 할 경우 - 호출측에서의 응답시간, 호출한 domain(ip)/url, 외부 호출, 쿼리나 crud table 정보 등)
아래 소스는 scouter client 소스이니 참고할 부분 있으시면 참고하시기 바랍니다.
https://github.com/scouter-project/scouter/blob/master/scouter.client/src/scouter/client/xlog/views/XLogFlowView.java

**Comment by kranian** [comment]
네 알겠습니다. 내용 분석 진행 하도록 하겠습니다.
