### ISSUE TITLE
hikaricp 정보가 나오지 않습니다.

### ISSUE THREAD

**Issue by JangCool** [scouter-contrib/scouter-paper#234]
안녕하세요.
scouter paper를 이용하여 대시보드를 활용하려고 하는데요.

scouter agent에는 hikaricp 정보를 볼 수 있다고 되어 있는데 페이퍼에서는 안나오더라구요

먼가 설정을 해줘야 하나요? 지원이 안되는건가요?

**Comment by kranian** [comment]
어떤 문서를 참고해서 했는지는 모르겠지만 현재 scouter 에이전트에서 hikaricp 정보가 수집되는 정보는 아닙니다. 현재 계획으로는 scouter2에서  개선할 예정입니다.

**Comment by JangCool** [comment]
https://www.facebook.com/groups/scouterapm/permalink/2123252627989573/

추적 기능이 있다 그래서요. 스카우터 2가 나올 예정이군요.

**Comment by gunlee01** [comment]
추적기능은 프로파일에 getConnection 호츨이 표시되는걸 의미합니다~

**Comment by kranian** [comment]
최근 질의응답이 없어 이슈 종료합니다.
