### ISSUE TITLE
paper 최초 로그인시 scouter web api server info 부분의 defaual 값 수정 방법

### ISSUE THREAD

**Issue by spc1jh** [scouter-contrib/scouter-paper#235]
안녕하세요 paper를 잘 활용하고 있습니다. 

문의사항이 있는데 최초 로그인시 paper의 웹세팅을 변경하고 싶습니다. 
한번 설정하면 계속해서 쓰는데는 문제는 없지만 
새로운 사람에게 해당 URL을 전달시마다 계속해서 알려주기가 불편합니다. 

![Untitled](https://user-images.githubusercontent.com/47548767/66011114-b456f500-e4fc-11e9-8881-8cdecff749dc.png)

첨부와 같은 부분의 세팅값을 예를 들어 port 6100 authentication type 을 cookie 와같이 서버에서 세팅 변경하는 방법이 있는지 알려주시기 바랍니다. 
지금은 첨부의 빨간 테두리와 같이 default로 세팅되어 있습니다. 

해당 값을 변경해놓으면 모르는 사람이 URL과 계정 정보만 알면 바로 로그인할수 있을테니까요.
지금은 URL을 알아도 setting으로 들어가 해당 값을 제가 설명한 값으로 수정후 진입할수 있습니다.

**Comment by kranian** [comment]
답변이 늦었네요.  기본값 포트, 인증 부분 변경은 아직 없는것으로 확인됩니다. 

대신 Paper 최신 버전에는 자신이 보고 있는 대시보드를 상단 주소를 카피해서 다른 한테 전달하면 상대방도 내가보고 있는 화면을 그대로 보여주는 기능이 내재 되어 있습니다. 

예를 아래 주소를 드래인 카피 해서 자신의 브라우저에 입력하면 그대로 스카우터 데모 서버의 대시보드가 보여줍니다. 

# 스카우터 페이버 대시보드 (데모) 주소 
http://demo.scouterapm.com:6188/extweb/index.html#/paper?objects=1463674242%2C-1180057655%2C-30645576%2C2033927919%2C1291312847%2C911699808%2C1315531795%2C-1502713930%2C1139150454%2C29763814%2C1026166527&realtime=true&longterm=false&from=20190604110300&to=20190604111300&address=demo.scouterapm.com&port=6188&protocol=http&fromPast=true

# 스카우터 페이버  대시보드 (데모)
![image](https://user-images.githubusercontent.com/18545293/66254349-0b382500-e7b0-11e9-9780-a4b9d7107362.png)

그럼 수고하세요
