### ISSUE TITLE
Setting > Xlog Configuration에 Classic mode 옵션 추가.

### ISSUE THREAD

**Issue by gunlee01** [scouter-contrib/scouter-paper#242]
### classic mode 선택 - 체크박스
* 선택하게 되면 xlog가 클래식(현재 전용 클라이언트) 모양으로 한번에 적용된다.
  * RCP 클라이언트와 같은 풍차 모양 / 투명도 없음 / 흰색 부분도 불투명한 흰색임 
      (이 경우 일정 수준으로 겹칠때 어느정도 겹쳐 있는지를 어느정도 유추가 가능함)
  * classic mode인 경우에는 인스턴스 별 xlog 점(풍차)의 색이 다르게 된다.
      단 에러등의 표시와 혼동을 방지하지 않기 위해 진한 레드계열 / 완전한 회색(비동기)는 사용하지 않는다.

**Comment by kranian** [comment]
# XLOG 설정에  클래스 모드 추가 
![image](https://user-images.githubusercontent.com/18545293/68928481-850af780-07cd-11ea-99b2-a0bb2dfab72f.png)

# XLOG 설정에  클래스 모드 동작 결과 
![image](https://user-images.githubusercontent.com/18545293/68928559-aff54b80-07cd-11ea-8719-286e919c9494.png)
