### ISSUE TITLE
프로파일에 에러 표시

### ISSUE THREAD

**Issue by gunlee01** [scouter-contrib/scouter-paper#243]
현재 에러가 표시되지 않고 있는데 에러가 표시되면 좋을 것 같습니다.

![image](https://user-images.githubusercontent.com/6788732/68269196-3c03c680-009c-11ea-90ed-a4193defc63b.png)

**Comment by kranian** [comment]
![image](https://user-images.githubusercontent.com/18545293/68301183-bf480b00-00e2-11ea-8e72-95e7e2730634.png)
