### ISSUE TITLE
xlog 필터창에 확인 버튼 선택 불가

### ISSUE THREAD

**Issue by gunlee01** [scouter-contrib/scouter-paper#244]
이전 버전에서는 필터창이 xlog창 영역내에 열렸고 스크롤바가 생겼던 것으로 기억합니다.
현재는 스크롤이 되지 않아 필터창에서 확인 버튼을 누를수가 없습니다.

아니면 필터창을 xlog창 영역내가 아닌 전체 브라우저 위로 올리는 방법도 좋을 듯 합니다.
(가능한지는 모르겠으나...)

![image](https://user-images.githubusercontent.com/6788732/68269266-79685400-009c-11ea-91fc-7d4f48937911.png)

**Comment by david100gom** [comment]
@gunlee01 제가 필터 작업할때에도 스크롤이 있었던 기억이 ....

**Comment by kranian** [comment]
리눅스 크롬 브라우저 하고, 윈도우 크롬 브라우저 차이가  있나 보군요 확인 해봐야겠어요

**Comment by kranian** [comment]
윈도우에서 현상이 제현이 돼서 확인해 볼게요
