### ISSUE TITLE
v2.6.2 preview - Xlog classic 모드 관련

### ISSUE THREAD

**Issue by gunlee01** [scouter-contrib/scouter-paper#246]
### 명칭
 - classic mode로 변경 부탁드립니다.

### xlog 색상이 인스턴스별로 섞여 보이지 않는 현상? 
 - 느낌상 일정 구간이 거의 동일한 색으로 보여지는데(색이 섞여보이지 않고...)
   뭔가 인스턴스별 순서로 색칠해서 그런가요? 
![image](https://user-images.githubusercontent.com/6788732/69016657-bfe67880-09e3-11ea-8ba3-11791093eb47.png)
![image](https://user-images.githubusercontent.com/6788732/69016665-d1c81b80-09e3-11ea-8176-4c4f54f3e276.png)

### xlog 색이 계속 변경된다.
 - 동영상 첨부...
 - https://youtu.be/IpKMpXOO4D4

**Comment by kranian** [comment]
네 맞습니다. 인스턴스별 순서로 색칠해서 그렇습니다. 이 부분은 보완 하도록 할게요.

**Comment by kranian** [comment]
xlog 색상이 인스턴스별로 섞여 보이지 현상 수정 및 오타 수정 했어요. 다시 테스트 할때는  Config 설정을 지워야  합니다. 브라우저 내에 내장된 LocalStorge에서 scouter paper 설정을  삭제 하세요

**Comment by kranian** [comment]
- 색상이 인스턴별로 섞여 보이도록 수정 완료 

![색상이 섞이지 않는 현상-수정](https://user-images.githubusercontent.com/18545293/69026625-feddf380-0a0e-11ea-9bf1-68e056eda494.gif)

**Comment by kranian** [comment]
* QA 체크 리스트 목록 
  -  실시간/과거  
     - [ ] 인스턴스 셀렉터를 통한 필터링 XLog 여부 확인
     - [ ] XLog Classic 모드   N -> Y 확인
     - [ ] XLog Classic 모드   Y -> N 확인
     - [ ] XLog 인스턴스 별 컬러 표시 여부 확인
     - [ ] XLog 축 0초, Max 초 표시가 잘 이전 보다 잘보이지는 여부 확인 
     - [ ] XLog 드래그 이벤트시 프로파일 조회 기능 정상 동작 확인 
   - 블랙 테마 
     - [ ] XLog  Classic 모드 컬러 표시 확인
