### ISSUE TITLE
안녕하세요. service 및 referrer 관련 질문 드립니다.

### ISSUE THREAD

**Issue by rornfdlek** [scouter-contrib/scouter-paper#255]
안녕하세요.
scouter와 paper를 이용하던 중 질문이 있어 글을 올립니다.

paper에서 profiler 목록에 조회되는 row들의 상세 정보에 service 와 referrer 가 있는데, 
혹시 service 도 referrer 와 같이 full url 형태로 request url (쿼리스트링, POST 파라미터 포함)을 제공 받을 수 있을까요?
referrer 는 이전 페이지를 나타낸다고 알고 있는데, 현재 서비스가 작동 중인 페이지의 full request  url이 필요해서요...

혹시 서버나 에이전트에 따로 config 변경이 필요하다면 해당 설정값들을 알려주시면 감사하겠습니다.

답변 부탁드립니다.
감사합니다.

**Comment by kranian** [comment]
결론 부터 드라자면 현재 서비스가 작동 중인 페이지의 full request url 정보는  request url (쿼리스트링, POST 파라미터 포함)는 특정 프로파일 리스트 필드 화면에는 노출 되지는 않습니다.  이유는 프로파일 STEP 기준으로 수집돼서 그렇습니다.  수집된 쿼리스링과 , POST 파라미터를 확인 하기 위해서는 프로파일 상세 페이지에서 제일 상단 MSG STEP 에서 내용을 확인 할수 있습니다. 

![image](https://user-images.githubusercontent.com/18545293/80439504-a86fcc00-8941-11ea-977b-4686e774e532.png)

에이전트 쿼리스트링, POST 파라미터 포함 수집 하려면 아래의 설정을 적용 하면 됩니다. 
 -  profile_http_querystring_enabled=true 
 -  profile_http_header_enabled=true  <= 이설정을 적용해 보시고  POST 파라미터 포함 돼서 수집이 되는지 확인 한번 확인을 해보세요 

다른 방법으로는 에이전트 기준 httpservice 플러그인을  사용해 커스텀 프로파일 방법으로 원하는 full request url 형태로 변환해서 사용하실수 있습니다. 단점은 해당 부분에 사용 사례가 많이 없네요 ㅠ.ㅠ 

그럼 수고하세요
